version: "3.5"
services:
  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "${CADDY_PORT}:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/certificate.pem:/etc/ssl/certs/certificate.pem
      - $PWD/key.pem:/etc/ssl/private/key.pem
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - aq-network

  site:
    build:
      context: .
      dockerfile: ./Dockerfile.site
      args:
        PUBLIC_SITE_URL: $PUBLIC_SITE_URL
    depends_on:
      - backend
    networks:
      - aq-network
    env_file:
      - .env
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    depends_on:
      - redis
      - postgres
    networks:
      - aq-network
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - aq-network

  postgres:
    container_name: postgres
    image: postgres:13.5
    networks:
      - aq-network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5434:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - postgres:/root/.pgadmin
    env_file:
      - .env
    networks:
      - aq-network

  meilisearch:
    image: getmeili/meilisearch:v0.27.0
    container_name: meilisearch
    volumes:
      - meili_data:/meili_data
    env_file:
      - .env
    networks:
      - aq-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - $PWD/packages/backend/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - aq-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=12345
    ports:
      - '3003:3000'
    networks:
      - aq-network

networks:
  aq-network:
    driver: bridge
    name: aq-network

volumes:
  caddy_data:
  caddy_config:
  postgres:
  meili_data:
  grafana-storage:
