version: "3.5"
services:
  site:
    build:
      context: .
      dockerfile: ./Dockerfile.site
      args:
        PUBLIC_SITE_URL: http://localhost:3000
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - aq-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - aq-network
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:13.5
    networks:
      - aq-network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5434:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  # meilisearch:
  #   image: getmeili/meilisearch:v0.28.1
  #   container_name: meilisearch
  #   volumes:
  #     - meili_data:/meili_data
  #   env_file:
  #     - .env
  #   networks:
  #     - aq-network

networks:
  aq-network:
    driver: bridge
    name: aq-network

volumes:
  postgres: # meili_data:
