services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/aqaratech/aqtech.git
    region: frankfurt
    plan: Standard
    branch: render-caddy
    dockerfilePath: ./Dockerfile.backend
    # numInstances: 1
    # maxInstances: 1
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: elephant
          property: connectionString
      - key: PORT
        value: 3002
    buildFilter:
      paths:
        - packages/backend/**
      ignoredPaths:
        - packages/backend/**/*.spec.ts

  # Sveltekit site
  - type: web
    name: site
    env: docker
    repo: https://github.com/aqaratech/aqtech.git
    region: frankfurt
    plan: standard
    branch: render-caddy
    dockerfilePath: ./Dockerfile.site
    healthCheckPath: /health
    envVars:
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: VITE_SITE_URL
        sync: false
      - key: VITE_API_URL
        sync: false
      - key: VITE_API_URL_LOCAL
        fromService:
          name: backend
          type: web
          property: hostport
      - key: PORT
        value: 3000
    buildFilter:
      paths:
        - packages/site/**
        - packages/sdk/**
      ignoredPaths:
        - packages/site/**/*.spec.ts

databases:
  - name: elephant
    region: frankfurt
    plan: Standard
