services:
  - type: web
    name: backend
    region: frankfurt
    env: docker
    dockerfilePath: ./Dockerfile.backend
    repo: https://github.com/aqaratech/aqtech.git
    branch: initNestjs
    plan: Starter Plus
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: PUBLIC_SITE_URL
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: aqaratechdb
          property: connectionString
      - key: PORT
        value: 3002
    buildFilter:
      paths:
        - packages/backend/**
      ignoredPaths:
        - packages/backend/**/*.spec.ts

  # Sveltekit site
  - type: web
    name: site
    region: frankfurt
    env: docker
    dockerfilePath: ./Dockerfile.site
    repo: https://github.com/aqaratech/aqtech.git
    branch: initNestjs
    plan: Starter Plus
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: PUBLIC_SITE_URL
        sync: false
      - key: PUBLIC_API_URL
        sync: false
      - key: PUBLIC_API_URL_LOCAL
        sync: false
      - key: PORT
        value: 3000
    buildFilter:
      paths:
        - packages/site/**
        - packages/sdk/**
      ignoredPaths:
        - packages/site/**/*.spec.ts

databases:
  - name: aqaratechdb
    region: frankfurt
    plan: Standard
