/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UnitVacancyDto,
    UnitVacancyDtoFromJSON,
    UnitVacancyDtoFromJSONTyped,
    UnitVacancyDtoToJSON,
} from './UnitVacancyDto';

/**
 * 
 * @export
 * @interface PaginatedResponseOfUnitVacancyDtoAllOf
 */
export interface PaginatedResponseOfUnitVacancyDtoAllOf {
    /**
     * 
     * @type {Array<UnitVacancyDto>}
     * @memberof PaginatedResponseOfUnitVacancyDtoAllOf
     */
    results?: Array<UnitVacancyDto>;
}

export function PaginatedResponseOfUnitVacancyDtoAllOfFromJSON(json: any): PaginatedResponseOfUnitVacancyDtoAllOf {
    return PaginatedResponseOfUnitVacancyDtoAllOfFromJSONTyped(json, false);
}

export function PaginatedResponseOfUnitVacancyDtoAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfUnitVacancyDtoAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(UnitVacancyDtoFromJSON)),
    };
}

export function PaginatedResponseOfUnitVacancyDtoAllOfToJSON(value?: PaginatedResponseOfUnitVacancyDtoAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(UnitVacancyDtoToJSON)),
    };
}

