/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PaginatedDto,
    PaginatedDtoFromJSON,
    PaginatedDtoFromJSONTyped,
    PaginatedDtoToJSON,
} from './PaginatedDto';

/**
 * 
 * @export
 * @interface PaginatedMetaDto
 */
export interface PaginatedMetaDto {
    /**
     * 
     * @type {PaginatedDto}
     * @memberof PaginatedMetaDto
     */
    meta: PaginatedDto;
}

export function PaginatedMetaDtoFromJSON(json: any): PaginatedMetaDto {
    return PaginatedMetaDtoFromJSONTyped(json, false);
}

export function PaginatedMetaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedMetaDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'meta': PaginatedDtoFromJSON(json['meta']),
    };
}

export function PaginatedMetaDtoToJSON(value?: PaginatedMetaDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'meta': PaginatedDtoToJSON(value.meta),
    };
}

