/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDto,
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
} from './UserDto';

/**
 * 
 * @export
 * @interface PaginatedResponseOfUserDtoAllOf
 */
export interface PaginatedResponseOfUserDtoAllOf {
    /**
     * 
     * @type {Array<UserDto>}
     * @memberof PaginatedResponseOfUserDtoAllOf
     */
    results?: Array<UserDto>;
}

export function PaginatedResponseOfUserDtoAllOfFromJSON(json: any): PaginatedResponseOfUserDtoAllOf {
    return PaginatedResponseOfUserDtoAllOfFromJSONTyped(json, false);
}

export function PaginatedResponseOfUserDtoAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfUserDtoAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(UserDtoFromJSON)),
    };
}

export function PaginatedResponseOfUserDtoAllOfToJSON(value?: PaginatedResponseOfUserDtoAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(UserDtoToJSON)),
    };
}

