/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LeaseInvoiceDto,
    LeaseInvoiceDtoFromJSON,
    LeaseInvoiceDtoFromJSONTyped,
    LeaseInvoiceDtoToJSON,
} from './LeaseInvoiceDto';

/**
 * 
 * @export
 * @interface PaginatedResponseOfLeaseInvoiceDtoAllOf
 */
export interface PaginatedResponseOfLeaseInvoiceDtoAllOf {
    /**
     * 
     * @type {Array<LeaseInvoiceDto>}
     * @memberof PaginatedResponseOfLeaseInvoiceDtoAllOf
     */
    results?: Array<LeaseInvoiceDto>;
}

export function PaginatedResponseOfLeaseInvoiceDtoAllOfFromJSON(json: any): PaginatedResponseOfLeaseInvoiceDtoAllOf {
    return PaginatedResponseOfLeaseInvoiceDtoAllOfFromJSONTyped(json, false);
}

export function PaginatedResponseOfLeaseInvoiceDtoAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfLeaseInvoiceDtoAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(LeaseInvoiceDtoFromJSON)),
    };
}

export function PaginatedResponseOfLeaseInvoiceDtoAllOfToJSON(value?: PaginatedResponseOfLeaseInvoiceDtoAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(LeaseInvoiceDtoToJSON)),
    };
}

