/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExpenseDto,
    ExpenseDtoFromJSON,
    ExpenseDtoFromJSONTyped,
    ExpenseDtoToJSON,
} from './ExpenseDto';
import {
    PaginatedDto,
    PaginatedDtoFromJSON,
    PaginatedDtoFromJSONTyped,
    PaginatedDtoToJSON,
} from './PaginatedDto';
import {
    PaginatedMetaDto,
    PaginatedMetaDtoFromJSON,
    PaginatedMetaDtoFromJSONTyped,
    PaginatedMetaDtoToJSON,
} from './PaginatedMetaDto';
import {
    PaginatedResponseOfExpenseDtoAllOf,
    PaginatedResponseOfExpenseDtoAllOfFromJSON,
    PaginatedResponseOfExpenseDtoAllOfFromJSONTyped,
    PaginatedResponseOfExpenseDtoAllOfToJSON,
} from './PaginatedResponseOfExpenseDtoAllOf';

/**
 * 
 * @export
 * @interface PaginatedResponseOfExpenseDto
 */
export interface PaginatedResponseOfExpenseDto {
    /**
     * 
     * @type {PaginatedDto}
     * @memberof PaginatedResponseOfExpenseDto
     */
    meta: PaginatedDto;
    /**
     * 
     * @type {Array<ExpenseDto>}
     * @memberof PaginatedResponseOfExpenseDto
     */
    results?: Array<ExpenseDto>;
}

export function PaginatedResponseOfExpenseDtoFromJSON(json: any): PaginatedResponseOfExpenseDto {
    return PaginatedResponseOfExpenseDtoFromJSONTyped(json, false);
}

export function PaginatedResponseOfExpenseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfExpenseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'meta': PaginatedDtoFromJSON(json['meta']),
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ExpenseDtoFromJSON)),
    };
}

export function PaginatedResponseOfExpenseDtoToJSON(value?: PaginatedResponseOfExpenseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'meta': PaginatedDtoToJSON(value.meta),
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ExpenseDtoToJSON)),
    };
}

