/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TenantDto,
    TenantDtoFromJSON,
    TenantDtoFromJSONTyped,
    TenantDtoToJSON,
} from './TenantDto';

/**
 * 
 * @export
 * @interface PaginatedResponseOfTenantDtoAllOf
 */
export interface PaginatedResponseOfTenantDtoAllOf {
    /**
     * 
     * @type {Array<TenantDto>}
     * @memberof PaginatedResponseOfTenantDtoAllOf
     */
    results?: Array<TenantDto>;
}

export function PaginatedResponseOfTenantDtoAllOfFromJSON(json: any): PaginatedResponseOfTenantDtoAllOf {
    return PaginatedResponseOfTenantDtoAllOfFromJSONTyped(json, false);
}

export function PaginatedResponseOfTenantDtoAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfTenantDtoAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(TenantDtoFromJSON)),
    };
}

export function PaginatedResponseOfTenantDtoAllOfToJSON(value?: PaginatedResponseOfTenantDtoAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(TenantDtoToJSON)),
    };
}

