/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyDto
 */
export interface PropertyDto {
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    readonly id: string;
    /**
     * 
     * @type {Date}
     * @memberof PropertyDto
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PropertyDto
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    block?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    avenue?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    street?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    number?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    parcel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    paci?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PropertyDto
     */
    cost?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    portfolioId: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    area: string | null;
}

export function PropertyDtoFromJSON(json: any): PropertyDto {
    return PropertyDtoFromJSONTyped(json, false);
}

export function PropertyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'block': !exists(json, 'block') ? undefined : json['block'],
        'avenue': !exists(json, 'avenue') ? undefined : json['avenue'],
        'street': !exists(json, 'street') ? undefined : json['street'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'parcel': !exists(json, 'parcel') ? undefined : json['parcel'],
        'paci': !exists(json, 'paci') ? undefined : json['paci'],
        'cost': !exists(json, 'cost') ? undefined : json['cost'],
        'portfolioId': json['portfolioId'],
        'area': json['area'],
    };
}

export function PropertyDtoToJSON(value?: PropertyDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'block': value.block,
        'avenue': value.avenue,
        'street': value.street,
        'number': value.number,
        'parcel': value.parcel,
        'paci': value.paci,
        'cost': value.cost,
        'portfolioId': value.portfolioId,
        'area': value.area,
    };
}

