/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyDto
 */
export interface PropertyDto {
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    readonly id: string;
    /**
     * 
     * @type {Date}
     * @memberof PropertyDto
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PropertyDto
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    portfolioId: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    area: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    block: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    avenue: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    street: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    number: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    parcel: string | null;
    /**
     * 
     * @type {string}
     * @memberof PropertyDto
     */
    paci: string | null;
    /**
     * 
     * @type {number}
     * @memberof PropertyDto
     */
    cost: number | null;
}

export function PropertyDtoFromJSON(json: any): PropertyDto {
    return PropertyDtoFromJSONTyped(json, false);
}

export function PropertyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'portfolioId': json['portfolioId'],
        'area': json['area'],
        'block': json['block'],
        'avenue': json['avenue'],
        'street': json['street'],
        'number': json['number'],
        'parcel': json['parcel'],
        'paci': json['paci'],
        'cost': json['cost'],
    };
}

export function PropertyDtoToJSON(value?: PropertyDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'portfolioId': value.portfolioId,
        'area': value.area,
        'block': value.block,
        'avenue': value.avenue,
        'street': value.street,
        'number': value.number,
        'parcel': value.parcel,
        'paci': value.paci,
        'cost': value.cost,
    };
}

