/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BreadcrumbDto,
    BreadcrumbDtoFromJSON,
    BreadcrumbDtoFromJSONTyped,
    BreadcrumbDtoToJSON,
} from './BreadcrumbDto';

/**
 * 
 * @export
 * @interface PropertyBreadcrumbsDtoPortfolio
 */
export interface PropertyBreadcrumbsDtoPortfolio {
    /**
     * 
     * @type {string}
     * @memberof PropertyBreadcrumbsDtoPortfolio
     */
    rel: PropertyBreadcrumbsDtoPortfolioRelEnum;
    /**
     * 
     * @type {string}
     * @memberof PropertyBreadcrumbsDtoPortfolio
     */
    href: string;
}


/**
 * @export
 */
export const PropertyBreadcrumbsDtoPortfolioRelEnum = {
    Tenant: 'Tenant',
    Portfolio: 'Portfolio',
    Property: 'Property',
    Unit: 'Unit',
    Lease: 'Lease',
    MaintenanceOrder: 'Maintenance Order'
} as const;
export type PropertyBreadcrumbsDtoPortfolioRelEnum = typeof PropertyBreadcrumbsDtoPortfolioRelEnum[keyof typeof PropertyBreadcrumbsDtoPortfolioRelEnum];


export function PropertyBreadcrumbsDtoPortfolioFromJSON(json: any): PropertyBreadcrumbsDtoPortfolio {
    return PropertyBreadcrumbsDtoPortfolioFromJSONTyped(json, false);
}

export function PropertyBreadcrumbsDtoPortfolioFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyBreadcrumbsDtoPortfolio {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rel': json['rel'],
        'href': json['href'],
    };
}

export function PropertyBreadcrumbsDtoPortfolioToJSON(value?: PropertyBreadcrumbsDtoPortfolio | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rel': value.rel,
        'href': value.href,
    };
}

