/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UnitTenantDto,
    UnitTenantDtoFromJSON,
    UnitTenantDtoFromJSONTyped,
    UnitTenantDtoToJSON,
} from './UnitTenantDto';

/**
 * 
 * @export
 * @interface UnitLeaseDtoTenant
 */
export interface UnitLeaseDtoTenant {
    /**
     * 
     * @type {string}
     * @memberof UnitLeaseDtoTenant
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof UnitLeaseDtoTenant
     */
    shortName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UnitLeaseDtoTenant
     */
    fullName: string;
}

export function UnitLeaseDtoTenantFromJSON(json: any): UnitLeaseDtoTenant {
    return UnitLeaseDtoTenantFromJSONTyped(json, false);
}

export function UnitLeaseDtoTenantFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnitLeaseDtoTenant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'shortName': !exists(json, 'shortName') ? undefined : json['shortName'],
        'fullName': json['fullName'],
    };
}

export function UnitLeaseDtoTenantToJSON(value?: UnitLeaseDtoTenant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shortName': value.shortName,
        'fullName': value.fullName,
    };
}

