/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UnitLeaseDtoTenant,
    UnitLeaseDtoTenantFromJSON,
    UnitLeaseDtoTenantFromJSONTyped,
    UnitLeaseDtoTenantToJSON,
} from './UnitLeaseDtoTenant';

/**
 * 
 * @export
 * @interface UnitLeaseDto
 */
export interface UnitLeaseDto {
    /**
     * 
     * @type {string}
     * @memberof UnitLeaseDto
     */
    readonly id: string;
    /**
     * 
     * @type {Date}
     * @memberof UnitLeaseDto
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UnitLeaseDto
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {UnitLeaseDtoTenant}
     * @memberof UnitLeaseDto
     */
    tenant: UnitLeaseDtoTenant;
    /**
     * 
     * @type {string}
     * @memberof UnitLeaseDto
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof UnitLeaseDto
     */
    unitId: string;
    /**
     * 
     * @type {Date}
     * @memberof UnitLeaseDto
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof UnitLeaseDto
     */
    end: Date;
    /**
     * 
     * @type {number}
     * @memberof UnitLeaseDto
     */
    monthlyRent: number;
    /**
     * 
     * @type {number}
     * @memberof UnitLeaseDto
     */
    deposit: number;
    /**
     * 
     * @type {boolean}
     * @memberof UnitLeaseDto
     */
    deactivated: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UnitLeaseDto
     */
    notify: boolean;
    /**
     * 
     * @type {string}
     * @memberof UnitLeaseDto
     */
    license: string | null;
}

export function UnitLeaseDtoFromJSON(json: any): UnitLeaseDto {
    return UnitLeaseDtoFromJSONTyped(json, false);
}

export function UnitLeaseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnitLeaseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'tenant': UnitLeaseDtoTenantFromJSON(json['tenant']),
        'tenantId': json['tenantId'],
        'unitId': json['unitId'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'monthlyRent': json['monthlyRent'],
        'deposit': json['deposit'],
        'deactivated': json['deactivated'],
        'notify': json['notify'],
        'license': json['license'],
    };
}

export function UnitLeaseDtoToJSON(value?: UnitLeaseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tenant': UnitLeaseDtoTenantToJSON(value.tenant),
        'tenantId': value.tenantId,
        'unitId': value.unitId,
        'start': (value.start.toISOString()),
        'end': (value.end.toISOString()),
        'monthlyRent': value.monthlyRent,
        'deposit': value.deposit,
        'deactivated': value.deactivated,
        'notify': value.notify,
        'license': value.license,
    };
}

