/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnitDto
 */
export interface UnitDto {
    /**
     * 
     * @type {string}
     * @memberof UnitDto
     */
    readonly id: string;
    /**
     * 
     * @type {Date}
     * @memberof UnitDto
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UnitDto
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UnitDto
     */
    propertyId: string;
    /**
     * 
     * @type {string}
     * @memberof UnitDto
     */
    unitNumber: string;
    /**
     * 
     * @type {number}
     * @memberof UnitDto
     */
    floor: number | null;
    /**
     * 
     * @type {number}
     * @memberof UnitDto
     */
    size: number | null;
    /**
     * 
     * @type {number}
     * @memberof UnitDto
     */
    bed: number | null;
    /**
     * 
     * @type {number}
     * @memberof UnitDto
     */
    bath: number | null;
    /**
     * 
     * @type {number}
     * @memberof UnitDto
     */
    marketRent: number | null;
    /**
     * 
     * @type {string}
     * @memberof UnitDto
     */
    type: string | null;
    /**
     * 
     * @type {string}
     * @memberof UnitDto
     */
    usage: string | null;
}

export function UnitDtoFromJSON(json: any): UnitDto {
    return UnitDtoFromJSONTyped(json, false);
}

export function UnitDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnitDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'propertyId': json['propertyId'],
        'unitNumber': json['unitNumber'],
        'floor': json['floor'],
        'size': json['size'],
        'bed': json['bed'],
        'bath': json['bath'],
        'marketRent': json['marketRent'],
        'type': json['type'],
        'usage': json['usage'],
    };
}

export function UnitDtoToJSON(value?: UnitDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'propertyId': value.propertyId,
        'unitNumber': value.unitNumber,
        'floor': value.floor,
        'size': value.size,
        'bed': value.bed,
        'bath': value.bath,
        'marketRent': value.marketRent,
        'type': value.type,
        'usage': value.usage,
    };
}

