/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateExpenseDto
 */
export interface UpdateExpenseDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateExpenseDto
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateExpenseDto
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateExpenseDto
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateExpenseDto
     */
    unitId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateExpenseDto
     */
    propertyId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateExpenseDto
     */
    portfolioId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateExpenseDto
     */
    amount?: number;
    /**
     * 
     * @type {Date}
     * @memberof UpdateExpenseDto
     */
    postAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateExpenseDto
     */
    memo?: string | null;
}

export function UpdateExpenseDtoFromJSON(json: any): UpdateExpenseDto {
    return UpdateExpenseDtoFromJSONTyped(json, false);
}

export function UpdateExpenseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateExpenseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'unitId': !exists(json, 'unitId') ? undefined : json['unitId'],
        'propertyId': !exists(json, 'propertyId') ? undefined : json['propertyId'],
        'portfolioId': !exists(json, 'portfolioId') ? undefined : json['portfolioId'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'postAt': !exists(json, 'postAt') ? undefined : (new Date(json['postAt'])),
        'memo': !exists(json, 'memo') ? undefined : json['memo'],
    };
}

export function UpdateExpenseDtoToJSON(value?: UpdateExpenseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'unitId': value.unitId,
        'propertyId': value.propertyId,
        'portfolioId': value.portfolioId,
        'amount': value.amount,
        'postAt': value.postAt === undefined ? undefined : (value.postAt.toISOString()),
        'memo': value.memo,
    };
}

