alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_LIVE
  - rule: DOMAIN_FAILED
databases:
  - db_name: aqratechdb
    db_user: aqaratechdb
    engine: PG
    name: aqaratechdb
    num_nodes: 1
    production: false
    version: "14"
domains:
  - domain: stage.aqaratech.net
    type: PRIMARY
envs:
  - key: PUBLIC_SITE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}
  - key: PUBLIC_API_URL
    scope: RUN_AND_BUILD_TIME
    value: ${aqaratech-api.PUBLIC_URL}
  - key: PUBLIC_API_URL_LOCAL
    scope: RUN_AND_BUILD_TIME
    value: ${aqaratech-api.PRIVATE_URL}
  - key: AUTH0_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: uSR4Gjf3XNN-1kfZGuppDqRdbz7XD6A4o2g8yY1GdZgqCXeYhWhdqfPUoIIJLBRf
  - key: AQ_DEBUG_NEST
    scope: RUN_AND_BUILD_TIME
    value: "0"
  - key: AQ_DEBUG_PRISMA
    scope: RUN_AND_BUILD_TIME
    value: "0"
name: aqaratech-app
region: fra
services:
  - envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${aqaratechdb.DATABASE_URL}
    health_check:
      http_path: /health
    http_port: 3002
    image:
      registry_type: DOCR
      repository: aqaratech-api
      tag: latest
    instance_count: 1
    # instance_size_slug: professional-s
    # log_destinations:
    #   - logtail:
    #       token: uxNpiF4y2RbpN15nPsq3zuZB
    #     name: logtail-do-addon
    name: aqaratech-api
    routes:
      - path: /api
  - health_check:
      http_path: /
    http_port: 3000
    image:
      registry_type: DOCR
      repository: aqaratech-site
      tag: latest
    instance_count: 1
    # instance_size_slug: professional-xs
    # log_destinations:
    # - logtail:
    #     token: uxNpiF4y2RbpN15nPsq3zuZB
    #   name: logtail-do-addon
    name: aqaratech-site
    routes:
      - path: /
