alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_LIVE
  - rule: DOMAIN_FAILED
databases:
  - engine: PG
    name: db-stage
    num_nodes: 1
    size: db-s-dev-database
    version: '12'
    production: false
# domains:
#   - domain: aqaratech.com
#     type: PRIMARY
envs:
  - key: PUBLIC_SITE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}
  - key: PUBLIC_API_URL
    scope: RUN_AND_BUILD_TIME
    value: ${backend.PUBLIC_URL}
  - key: PUBLIC_API_URL_LOCAL
    scope: RUN_AND_BUILD_TIME
    value: ${backend.PRIVATE_URL}
  - key: PUBLIC_AQ_DEBUG_LEVEL
    scope: RUN_AND_BUILD_TIME
    value: 'verbose'
  - key: PUBLIC_AQARATECH_ENV
    scope: RUN_AND_BUILD_TIME
    value: staging
  - key: PUBLIC_TRACE_RATE
    scope: RUN_AND_BUILD_TIME
    value: '0.5'
  - key: LOGTAIL_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: qsYDfRpM2TXqyGeYhUNFReag
  - key: BODY_SIZE_LIMIT
    scope: RUN_AND_BUILD_TIME
    value: '15000000'
  - key: STRIPE_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: 'sk_test_51MFU85GjhXLpX9m0IPXC4T3TzGGoc7eYa4mx5v6PraQtwhJ1IRZCZY86ZmiNDk4bl6RPglUfUqGLY72cfIIdufRz00VNUyVPcP'
  - key: PUBLIC_TIER_PLAN_ID_1
    scope: RUN_AND_BUILD_TIME
    value: plan:core@1
  - key: PUBLIC_MYFATOORAH_SITE_URL
    scope: RUN_AND_BUILD_TIME
    value: https://demo.myfatoorah.com
name: REPLACE_NAME
region: fra
services:
  - name: backend
    image:
      registry_type: DOCR
      repository: aqaratech-backend
      tag: REPLACE_TAG_BACKEND
    routes:
      - path: /api
    instance_size_slug: professional-xs
    instance_count: 1
    http_port: 3002
    health_check:
      failure_threshold: 6
      http_path: /health
    alerts:
      - operator: GREATER_THAN
        rule: CPU_UTILIZATION
        value: 50
        window: FIVE_MINUTES
      - operator: GREATER_THAN
        rule: MEM_UTILIZATION
        value: 50
        window: FIVE_MINUTES
      - operator: GREATER_THAN
        rule: RESTART_COUNT
        value: 2
        window: FIVE_MINUTES
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db-stage.DATABASE_URL}
      - key: POSTMARK_TOKEN
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: aecd4fd3-1314-44e9-b1b5-d7dbb89fd0ca
      - key: R2_ENDPOINT
        scope: RUN_AND_BUILD_TIME
        value: https://8aa55983de332834393a9f4c4fbf1e35.r2.cloudflarestorage.com
      - key: R2_ACCESS_KEY_ID
        scope: RUN_AND_BUILD_TIME
        value: 19c40a5035eeb256b8e2fd59811c7203
      - key: R2_SECRET_ACCESS_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: 2493bd85d0e72adb6979a06c6385468653693f99dc8b108a655de336e3a04bb1
      - key: PUBLIC_ROUTE_PATH
        scope: RUN_AND_BUILD_TIME
        value: ${_self.PUBLIC_ROUTE_PATH}
      - key: MYFATOORAH_URL
        scope: RUN_AND_BUILD_TIME
        value: https://apitest.myfatoorah.com
      - key: MYFATOORAH_KEY
        scope: RUN_AND_BUILD_TIME
        value: 'Isy2OQPlrapEAp_uM4eWpZDhzmWCeyElhXRYhxzIOMDyi9eKYJzmkH7BYRGqgwSVsAQNJ50i9obH_BHuwsClPQc0V6sWGci9h_1FzigleH0jDo1TCcapqIXvuY3SODLWcBDYjjtz6tTTUNAuH7EoeCTo4KHqFSWC4UBTDP92gsVRv393VPnDiBgBtQNoAOLOfRFx_gBOoGEpw4QJ4Oki-ftqxk87f0KWcTc8EIjtNyKD5_pGy7tJ0dO-nn1_t1WpHLO96K6GpxVfR-pE5Ji765QLkOWrMELBWxdNILzeXwXPZDkZPES499eDgBqZB-ODDv6cS2JPD9JgSGSahmLlCwMgC0UuI0B4PcwqQcuzMgDl3esa0NBQC_LgwKRE4hb-mEU3gnqqcR18l8puTLI-Tjz4Z_7x4PJ_nAAkL94vWs4UnhgZNZULoWWSPESyI9R3vDN1IW8MF14IRjX5IdmAzAo4-dksseJLLDRAIbR_Tgdw1GxQtPf3njSzpq0EwQvXLh9wiZFgvZFHWhd8ncw5SEmoEqeNdpqR7onWW82CqCWmI7L-TaIaeTDIdk9_ep377mRmGlY72ZCVpSWLI4Gn3f1n8XnQM-Z92mjXASaSS6f2pbCpATSIa_vllKy9xh-CPAwHxrD6eVSbeRZmjPvLrGa8v3DuywYaHee5ffCmqyozYZDvrfvGeWWl80mzL7If8ZIxiQ'
      - key: NOVU_TOKEN
        scope: RUN_AND_BUILD_TIME
        value: 'abc'
  - name: site
    image:
      registry_type: DOCR
      repository: aqaratech-site
      tag: REPLACE_TAG_SITE
    instance_count: 1
    instance_size_slug: professional-xs
    routes:
      - path: /
    http_port: 3000
    health_check:
      failure_threshold: 6
      http_path: /health
    alerts:
      - operator: GREATER_THAN
        rule: CPU_UTILIZATION
        value: 50
        window: FIVE_MINUTES
      - operator: GREATER_THAN
        rule: MEM_UTILIZATION
        value: 50
        window: FIVE_MINUTES
      - operator: GREATER_THAN
        rule: RESTART_COUNT
        value: 2
        window: FIVE_MINUTES
    envs:
      - key: AUTH0_CLIENT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: uSR4Gjf3XNN-1kfZGuppDqRdbz7XD6A4o2g8yY1GdZgqCXeYhWhdqfPUoIIJLBRf
      - key: ORIGIN
        scope: RUN_AND_BUILD_TIME
        value: ${APP_URL}
