name: Deploy
description: Trigger deployment on DigitalOcean

inputs:
  token:
    required: true
    description: DigitalOcean Access Token
  projectId:
    required: true
    description: DigitalOcean Project ID
  appName:
    required: true
    description: DigitalOcean App Platform App Name - Must be unique per project
  siteVersion:
    required: true
    description: Version of the site to deploy
  backendVersion:
    required: true
    description: Version of the backend to deploy

runs:
  using: composite
  steps:
    - name: yq - portable yaml processor
      uses: mikefarah/yq@v4.27.5

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.token }}

    - name: Create deployment on DigitalOcean
      shell: bash
      run: |
        npx zx ./.do/deploy.mjs \
        --app-name ${{ inputs.appName }} \
        --site-version ${{ inputs.siteVersion }} \
        --backend-version ${{ inputs.backendVersion }}
