name: Deploy
description: Trigger deployment on DigitalOcean

inputs:
  token:
    required: true
    description: DigitalOcean Access Token
  projectId:
    required: true
    description: DigitalOcean Project ID
  appName:
    required: true
    description: DigitalOcean App Platform App Name - Must be unique per project
  siteTag:
    required: false
    description: Version of the site to deploy
  backendTag:
    required: false
    description: Version of the backend to deploy

outputs:
  deploy-url:
    description: 'The URL of the deployed app'
    value: ${{ steps.deploy-app.outputs.deploy-url }}

runs:
  using: composite
  steps:
    - name: yq - portable yaml processor
      uses: mikefarah/yq@v4.27.5

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.token }}

      # To output the deployment URL:
      # https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file
    - id: deploy-app
      name: Create deployment on DigitalOcean
      shell: bash
      run: |
        npx zx ./scripts/deploy.mjs \
        --app-name ${{ inputs.appName }} \
        --site-version ${{ inputs.siteTag }} \
        --backend-version ${{ inputs.backendTag }}

      # Causes error. Hint: use `continue-on-error` when debugging.
      # run: |
      #   npx zx ./scripts/deploy.mjs \
      #   --app-name ${{ inputs.appName }} \
      #   --site-version ${{ inputs.siteTag }} \
      #   --backend-version ${{ inputs.backendTag }} | tee deploy_output.log
      #   DEPLOY_URL=$(grep -oP '(?<="live_url": ")[^"]+' deploy_output.log | tail -n1)
      #   echo "deploy-url=$DEPLOY_URL" >> $GITHUB_OUTPUT
