export const areas: [string, string][] = [
	["Umm Al-Maradim Island", "جزيرة أم المرادم"],
	["Auha Island", "جزيرة عوهة"],
	["Mischan Island", "جزيرة مسكان"],
	["Dasman", "دسمان"],
	["Ardhiya Herafiya", "العارضية الحرفية"],
	["Al Bida'a", "البدع"],
	["Ministries Area", "منطقة الوزارات"],
	["Nuzha", "النزهة"],
	["Bnaid Al-Qar", "بنيد القار"],
	["Qadsiya", "القادسية"],
	["Nahda", "النهضة"],
	["Dasma", "الدسمة"],
	["Naeem", "النعيم"],
	["Rehab", "الرحاب"],
	["Yarmouk", "اليرموك"],
	["Sulaibiya Industrial 1", "الصليبية الصناعية 1"],
	["Omariya", "العمرية"],
	["Shuwaikh Industrial-3", "الشويخ الصناعية 3"],
	["Abdulla Al-Salem", "ضاحية عبدالله السالم"],
	["Riggai", "الرقعي"],
	["Adailiya", "العديلية"],
	["Shuwaikh Industrial-2", "الشويخ الصناعية 2"],
	["Sharq", "شرق"],
	["West Abdullah Al-Mubarak", "غرب عبدالله المبارك"],
	["Rawda", "الروضة"],
	["Qibla", "القبلة"],
	["Kifan", "كيفان"],
	["Surra", "السرة"],
	["Ghornata", "غرناطة"],
	["Abu Hassaniah", "أبو الحصانية"],
	["Northwest Sulaibikhat", "شمال غرب الصليبيخات"],
	["Al Sour Gardens", "حدائق السور"],
	["Shaab", "الشعب"],
	["Al-Siddiq", "الصديق"],
	["Hadiya", "هدية"],
	["Shuwaikh", "الشويخ"],
	["Rajim Khashman", "رجم خشمان"],
	["Ardhiya 4", "العارضية 4"],
	["Al-Fnaitees", "ضاحية الفنيطيس"],
	["Farwaniya", "الفروانية"],
	["Al-Qurain", "القرين"],
	["Zahra", "الزهراء"],
	["Al-Nuwaiseeb", "النويصيب"],
	["Al-Qusour", "القصور"],
	["Rumaithiya", "الرميثية"],
	["Shalehat Al-Nuwaiseeb", "شاليهات النويصيب"],
	["Mubarakiya Camps", "معسكرات المباركية"],
	["Middle of Ahmadi", "وسط الأحمدي"],
	["Janobyia Aljawakheer", "الجنوبية الجواخير"],
	["Qasr", "القصر"],
	["Al-Adan", "العدان"],
	["Hawalli", "حولي"],
	["Andalus", "الأندلس"],
	["Sabah Al-Nasser", "صباح الناصر"],
	["Health Area", "المنطقة الصحية"],
	["East Ahmadi", "شرق الأحمدي"],
	["Subhan Industrial", "صبحان الصناعية"],
	["South Ahmadi", "جنوب الأحمدي"],
	["Salwa", "سلوى"],
	["Jleeb Al-Shiyoukh", "جليب الشيوخ"],
	["Bayan", "بيان"],
	["Sabah Al-Salem", "صباح السالم"],
	["Jahra Industrial Herafiya 1", "الجهراء الصناعية الحرفية 1"],
	["Shalehat Jlea'a", "شاليهات الجليعة"],
	["Sabah Al-Salem University City", "مدينة صباح السالم الجامعية"],
	["Al-Fintas", "الفنطاس"],
	["South Al Mutlaa 2", "جنوب المطلاع 2"],
	["Shuwaikh Industrial-1", "الشويخ الصناعية 1"],
	["Shuaiba Industrial Western", "الشعيبه الصناعيه الغربيه"],
	["Fahaheel", "الفحيحيل"],
	["Mina Abdulla", "ميناء عبدالله"],
	["Kabd", "كبد"],
	["Shalehat Mina Abdullah", "شاليهات ميناء عبدالله"],
	["Shuaiba Industrial esterly", "الشعيبة الصناعية الشرقية"],
	["International Airport", "المطار الدولي"],
	["South Al Mutlaa 4", "جنوب المطلاع 4"],
	["Mina Al-Ahmadi Refinery", "مصفاة ميناء الأحمدي"],
	["Failaka Island", "جزيرة فيلكا"],
	["Zoor", "الزور"],
	["Sabah Al-Ahmad 2", "صباح الأحمد 2"],
	["Wista", "المنطقة الوسطى"],
	["Sabah Al-Ahmad 4", "صباح الأحمد 4"],
	["Sabah Al-Ahmad Investment", "صباح الأحمد استثمارية"],
	["Umm Al-Aish", "ام العيش"],
	["Sabah Al-Ahmad 3", "صباح الأحمد 3"],
	["Sabah Al-Ahmad 5", "صباح الأحمد 5"],
	["Rawdatain", "الروضتين"],
	["Wafra", "الوفرة"],
	["Al Masayel", "المسايل"],
	["Salam", "السلام"],
	["Sulaibikhat Cemetery", "مقبرة الصليبيخات"],
	["Anjafa", "أنجفة"],
	["South Al Mutlaa", "جنوب المطلاع"],
	["South Al Mutlaa 5", "جنوب المطلاع 5"],
	["South Al Mutlaa 7", "جنوب المطلاع 7"],
	["South Al Mutlaa 9", "جنوب المطلاع 9"],
	["South Al Mutlaa 12", "جنوب المطلاع 12"],
	["Bar Al-Jahra Governorate", "بر محافظة الجهراء"],
	["Ahmadi Governorate Desert", "بر محافظة الأحمدي"],
	["Shalehat Al-Khiran", "شاليهات الخيران"],
	["Qaruh Island", "جزيرة قاروه"],
	["Kubbar Island", "جزيرة كبر"],
	["Jawakher Al Jahra", "جواخير الجهراء"],
	["Mubarakyia", "المباركية"],
	["West Abu Ftirah Hirafyia", "غرب أبو فطيرة الحرفية"],
	["Mansouriya", "المنصورية"],
	["Ardhiya 6", "العارضية 6"],
	["Faiha", "الفيحاء"],
	["Dajeej", "ضجيج الطائرات"],
	["Waha", "الواحة"],
	["Mirqab", "المرقاب"],
	["Shamiya", "الشامية"],
	["Daiya", "الدعية"],
	["Oyoun", "العيون"],
	["Rabiya", "الرابية"],
	["Shalehat Zoor", "شاليهات الزور"],
	["Shuhada", "الشهداء"],
	["South Amghara", "جنوب أمغره"],
	["Khaldiya", "الخالدية"],
	["Umm Al-Namel Island", "جزيرة أم النمل"],
	["Khiran City", "الخيران السكنية"],
	["Mubarak Al-Abdullah", "مبارك العبدالله"],
	["Qortuba", "قرطبة"],
	["Fahad Al-Ahmad", "فهد الأحمد"],
	["North Ahmadi", "شمال الأحمدي"],
	["Ali Subah Al-Salem", "علي صباح السالم"],
	["Ashbeliah", "أشبيلية"],
	["Dhaher", "الظهر"],
	["South Al Mutlaa 11", "جنوب المطلاع 11"],
	["Hitteen", "حطين"],
	["Riqqa", "الرقة"],
	["Ferdous", "الفردوس"],
	["Jaber Al-Ali", "ضاحية جابر العلي"],
	["Jahra", "الجهراء"],
	["Messila", "المسيلة"],
	["Nasseem", "النسيم"],
	["Egaila", "العقيلة"],
	["Abu Ftaira", "ضاحية أبو فطيرة"],
	["Ardhiya", "العارضية"],
	["South-Sabahiya", "جنوب الصباحية"],
	["Al shadadyia Industrial", "الشدادية الصناعية"],
	["The Sea Front", "الواجهة البحرية"],
	["Abu Halifa", "أبو حليفة"],
	["Taima", "تيماء"],
	["Rai", "الري"],
	["Jabriya", "الجابرية"],
	["Mubarak Al-Kabeer", "مبارك الكبير"],
	["Mishrif", "مشرف"],
	["Kaerawan", "القيروان"],
	["Sabahiya", "الصباحية"],
	["Sulaibiya Industrial 2", "الصليبية الصناعية 2"],
	["Sulaibiya", "الصليبية الشعبية"],
	["Khaitan", "خيطان"],
	["Mahboula", "المهبولة"],
	["North West Jahra", "شمال غرب الجهراء"],
	["Mangaf", "المنقف"],
	["Mina Abdullah Refinery", "مصفاة ميناء عبدالله"],
	["Doha", "الدوحة"],
	["Shalehat Doha", "شاليهات الدوحة"],
	["Sulaibyia Industrial 3", "الصليبية الصناعية 3"],
	["Amghara Industrial", "أمغرة الصناعية"],
	["Shuwaikh Port", "المنطقة الحرة"],
	["Abdullah Mubarak Al-Sabah", "عبدالله مبارك الصباح"],
	["Saad Al-Abdulla City", "مدينة سعد العبدالله"],
	["Shalehat Dba'ayeh", "شاليهات الضباعية"],
	["Jaber Al-Ahmad", "جابر الأحمد"],
	["South Al Mutlaa 3", "جنوب المطلاع 3"],
	["Warba Island", "جزيرة وربة"],
	["Salmiya", "السالمية"],
	["Magwa", "المقوع"],
	["Al Naayem", "النعايم"],
	["Abdally", "العبدلي"],
	["Salmy", "السالمي"],
	["Jahra Camps", "معسكرات الجهراء"],
	["Sabah Al-Ahmad Services", "صباح الأحمد الخدمية"],
	["Mina Doha", "ميناء الدوحة"],
	["Shalehat Subiya", "شاليهات الصبية"],
	["Bhaith", "البحيث"],
	["Shalehat Bneder", "شاليهات بنيدر"],
	["Sabah Al-Ahmad 6", "صباح الأحمد 6"],
	["Shalehat Kazima", "شاليهات كاظمة"],
	["Kazima", "كاظمة"],
	["Sabah Al-Ahmad 1", "صباح الأحمد 1"],
	["Subiya", "الصبية"],
	["Bubyan Island", "جزيرة بوبيان"],
	["Sulaibiya Agricultural", "الصليبية الزراعية"],
	["New Wafra", "الوفرة الجديدة"],
	["Wafra Farms", "مزارع الوفرة"],
	["Sulaibikhat", "الصليبيخات"],
	["Al Mutlaa", "المطلاع"],
	["South Al Mutlaa 1", "جنوب المطلاع 1"],
	["South Al Mutlaa 6", "جنوب المطلاع 6"],
	["South Al Mutlaa 8", "جنوب المطلاع 8"],
	["South Al Mutlaa 10", "جنوب المطلاع 10"],
	["South Abdullah Al-Mubarak", "جنوب عبدالله المبارك"],
	["Al Sheqaya", "الشقايا"],
	["Sabah Al-Ahmad Al-marine", "صباح الاحمد البحرية"],
	["kabd Agricultural", "كبد الزراعية"],
];

export const coordinates: [number, number][] = [
	[29.14, 48.12],
	[29.12, 48.13],
	[29.09, 48.06],
	[29.26, 48.08],
	[29.15, 48.13],
	[28.88, 48.17],
	[29.08, 48.14],
	[29.17, 48.1],
	[29.09, 48.09],
	[29.1, 48.14],
	[29.24, 47.97],
	[29.19, 48.02],
	[29.17, 47.58],
	[29.2, 48.04],
	[29.28, 48.01],
	[29.24, 47.97],
	[29.24, 47.97],
	[29.24, 47.97],
	[29.27, 48.03],
	[29.34, 48.02],
	[29.34, 48.04],
	[29.27, 48.09],
	[29.28, 48.05],
	[29.34, 48.04],
	[29.33, 48.07],
	[29.19, 48.04],
	[29.3, 48.08],
	[29.34, 48.08],
	[29.35, 48.01],
	[29.33, 48.09],
	[29.35, 48.09],
	[29.34, 48.07],
	[29.32, 48.02],
	[29.34, 48.07],
	[29.28, 48.07],
	[29.27, 48.05],
	[29.29, 47.97],
	[29.35, 48.02],
	[29.34, 48.03],
	[29.33, 48.09],
	[29.34, 48.08],
	[29.34, 48.09],
	[29.32, 48.03],
	[29.33, 48.08],
	[29.34, 48.07],
	[29.36, 47.97],
	[29.29, 47.9],
	[29.35, 47.67],
	[29.34, 47.96],
	[29.33, 47.91],
	[29.19, 47.58],
	[29.19, 47.58],
	[29.19, 47.58],
	[29.33, 47.96],
	[29.38, 47.98],
	[29.21, 47.56],
	[29.33, 47.94],
	[29.32, 47.83],
	[29.12, 48.14],
	[29.38, 48],
	[29.37, 47.97],
	[29.34, 47.95],
	[29.34, 47.95],
	[29.32, 48.09],
	[29.24, 47.9],
	[29.17, 48.1],
	[29.32, 47.97],
	[29.3, 47.93],
	[29.38, 47.99],
	[29.37, 47.98],
	[29.33, 47.95],
	[29.3, 48.09],
	[29.39, 47.98],
	[29.3, 47.94],
	[29.39, 47.99],
	[28.88, 48.16],
	[29.3, 47.9],
	[29.36, 48.01],
	[29.34, 47.94],
	[29.21, 48.1],
	[29.32, 48.02],
	[29.38, 47.98],
	[28.73, 48.28],
	[29.3, 47.93],
	[29.36, 47.96],
	[29.2, 48.05],
	[29.3, 47.93],
	[29.3, 47.94],
	[29.3, 47.94],
	[29.36, 47.96],
	[28.89, 48.23],
	[29.33, 47.98],
	[28.88, 48.17],
	[29.25, 48.04],
	[29.36, 47.97],
	[29.37, 47.97],
	[29.3, 47.94],
	[29.3, 47.93],
	[29.38, 47.98],
	[29.37, 47.98],
	[29.3, 47.93],
	[29.11, 48.06],
	[29.17, 48.06],
	[29.24, 48.09],
	[29.19, 48.09],
	[29.2, 48.09],
];

export const palette: { [key: string]: string[] } = {
	2: ["#003f5c", "#f95d6a"],
	3: ["#003f5c", "#bc5090", "#ffa600"],
	4: ["#003f5c", "#7a5195", "#ef5675", "#ffa600"],
	5: ["#003f5c", "#58508d", "#bc5090", "#ff6361", "#ffa600"],
	6: ["#003f5c", "#444e86", "#955196", "#dd5182", "#ff6e54", "#ffa600"],
	7: [
		"#003f5c",
		"#374c80",
		"#7a5195",
		"#bc5090",
		"#ef5675",
		"#ff764a",
		"#ffa600",
	],
	8: [
		"#003f5c",
		"#2f4b7c",
		"#665191",
		"#a05195",
		"#d45087",
		"#f95d6a",
		"#ff7c43",
		"#ffa600",
	],
};

export const getColor = (index: number, total: number) => {
	const size = Math.max(2, Math.min(total, 8));
	const backgroundColor = palette[size]?.[index];
	return backgroundColor;
};

// prettier-ignore
export const defaultExpenseCategoryTree = [
  {"id":"qo4vwc2cd8y8","labelEn":"CapEx","parentId":null,"labelAr":"المصاريف الرأسمالية","isGroup":true},
  {"id":"jdf7bkwhrvg1","labelEn":"Annual Contracts","parentId":"qo4vwc2cd8y8","labelAr":"عقود الصيانة السنوية","isGroup":true},
  {"id":"gesn1f0jgn5i","labelEn":"AC Contract","parentId":"jdf7bkwhrvg1","labelAr":"","isGroup":false},
  {"id":"8sgct9i8upkt","labelEn":"Elevator Contract","parentId":"jdf7bkwhrvg1","labelAr":"","isGroup":false},
  {"id":"gttf57wg0dgr","labelEn":"Fire Fighting Contract","parentId":"jdf7bkwhrvg1","labelAr":"","isGroup":false},
  {"id":"vpihvfp9bdzu","labelEn":"Other CapEx","parentId":"qo4vwc2cd8y8","labelAr":"","isGroup":true},
  {"id":"907g0a6brfi6","labelEn":"Waterproofing","parentId":"vpihvfp9bdzu","labelAr":"","isGroup":false},
  {"id":"k73r929knh3o","labelEn":"Renovation","parentId":"vpihvfp9bdzu","labelAr":"","isGroup":false},
  {"id":"215la0zaismu","labelEn":"Major repairs","parentId":"vpihvfp9bdzu","labelAr":"","isGroup":false},
  {"id":"k0jjzdsoe10e","labelEn":"Structural Integrity","parentId":"vpihvfp9bdzu","labelAr":"","isGroup":false},
  {"id":"spzc3oe5yu01","labelEn":"OpEx","parentId":null,"labelAr":"المصاريف التشغيلية","isGroup":true},
  {"id":"f1sdv9tska96","labelEn":"Legal & Financial","parentId":"spzc3oe5yu01","labelAr":"المصاريف القانونية","isGroup":true},
  {"id":"xwmxwycynk39","labelEn":"Attorneys Fee","parentId":"f1sdv9tska96","labelAr":"","isGroup":false},
  {"id":"76sefoh9dar6","labelEn":"Insurance","parentId":"f1sdv9tska96","labelAr":"","isGroup":false},
  {"id":"73yh8ipo0g1a","labelEn":"Bank charges","parentId":"f1sdv9tska96","labelAr":"","isGroup":false},
  {"id":"id3vi17dtpo6","labelEn":"Government","parentId":"spzc3oe5yu01","labelAr":"المصاريف الحكومية","isGroup":true},
  {"id":"gnmyjzremtel","labelEn":"Municipal fees","parentId":"id3vi17dtpo6","labelAr":"","isGroup":false},
  {"id":"fi4d781fe5s2","labelEn":"Government Stamps","parentId":"id3vi17dtpo6","labelAr":"","isGroup":false},
  {"id":"wian0or39eil","labelEn":"Government Paperwork","parentId":"id3vi17dtpo6","labelAr":"","isGroup":false},
  {"id":"3sdsvhoqfh3n","labelEn":"Government Violations","parentId":"id3vi17dtpo6","labelAr":"","isGroup":false},
  {"id":"t8eekc45k4gu","labelEn":"Salaries","parentId":"spzc3oe5yu01","labelAr":"رواتب الحارس","isGroup":true},
  {"id":"uga4cjl40zsz","labelEn":"Caretaker Wages","parentId":"t8eekc45k4gu","labelAr":"","isGroup":false},
  {"id":"xr62u1v3e3jx","labelEn":"Caretaker Vacation leave","parentId":"t8eekc45k4gu","labelAr":"","isGroup":false},
  {"id":"nytbo6fayev5","labelEn":"Caretaker pension","parentId":"t8eekc45k4gu","labelAr":"","isGroup":false},
  {"id":"gaco4e3zkuwl","labelEn":"Caretaker Insurance & resident permit","parentId":"t8eekc45k4gu","labelAr":"","isGroup":false},
  {"id":"c5suvpzctp8t","labelEn":"Utilities","parentId":"spzc3oe5yu01","labelAr":"خدمات الكهرباء والماء","isGroup":true},
  {"id":"0q7zvizkt2jk","labelEn":"Water Consumption","parentId":"c5suvpzctp8t","labelAr":"","isGroup":false},
  {"id":"8dpwa0oigzgj","labelEn":"Electrical Consumption","parentId":"c5suvpzctp8t","labelAr":"","isGroup":false},
  {"id":"nqnppbq1f1r1","labelEn":"Gas","parentId":"c5suvpzctp8t","labelAr":"","isGroup":false},
  {"id":"sjog8wa6a7pr","labelEn":"Trash","parentId":"c5suvpzctp8t","labelAr":"","isGroup":false},
  {"id":"zee3oc7cskmx","labelEn":"Repairs","parentId":"spzc3oe5yu01","labelAr":"خدمات الإصلاحات","isGroup":true},
  {"id":"wl1yj5qx4hgt","labelEn":"Central Ventilation","parentId":"zee3oc7cskmx","labelAr":"","isGroup":false},
  {"id":"2hqo464o8t8r","labelEn":"Paint repairs","parentId":"zee3oc7cskmx","labelAr":"","isGroup":false},
  {"id":"6olmw9xgornc","labelEn":"Doors repairs","parentId":"zee3oc7cskmx","labelAr":"","isGroup":false},
  {"id":"x5foxh2sby91","labelEn":"Glass repairs","parentId":"zee3oc7cskmx","labelAr":"","isGroup":false},
  {"id":"bplpyd1x1jul","labelEn":"Aluminum repairs","parentId":"zee3oc7cskmx","labelAr":"","isGroup":false},
  {"id":"yhdx8ars5gw5","labelEn":"Plasterwork repairs","parentId":"zee3oc7cskmx","labelAr":"","isGroup":false},
  {"id":"65aqqsnx8yiq","labelEn":"Electrical repairs","parentId":"zee3oc7cskmx","labelAr":"","isGroup":false},
  {"id":"pbxi6vaqtwld","labelEn":"Plumbing repairs","parentId":"zee3oc7cskmx","labelAr":"","isGroup":false},
  {"id":"ycfsvd14dm5a","labelEn":"Gypsum repairs","parentId":"zee3oc7cskmx","labelAr":"","isGroup":false},
  {"id":"3zqov7sa1u4x","labelEn":"Maintenance","parentId":"spzc3oe5yu01","labelAr":"خدمات الصيانة","isGroup":true},
  {"id":"ogh3ldklhj19","labelEn":"Property Maintenance","parentId":"3zqov7sa1u4x","labelAr":"","isGroup":false},
  {"id":"5kywl45mih9b","labelEn":"Amenities Maintenance","parentId":"3zqov7sa1u4x","labelAr":"","isGroup":false},
  {"id":"lnpal8aa0e0q","labelEn":"Apartment Maintenance","parentId":"3zqov7sa1u4x","labelAr":"","isGroup":false},
  {"id":"buv0zm7p9cxn","labelEn":"AC Maintenance","parentId":"3zqov7sa1u4x","labelAr":"","isGroup":false},
  {"id":"td7yj633c9sd","labelEn":"Elevator Maintenance","parentId":"3zqov7sa1u4x","labelAr":"","isGroup":false},
  {"id":"w62h7o6dag8u","labelEn":"Electrical Maintenance","parentId":"3zqov7sa1u4x","labelAr":"","isGroup":false},
  {"id":"xmqwqdc9lxga","labelEn":"Plumbing maintenance","parentId":"3zqov7sa1u4x","labelAr":"","isGroup":false},
  {"id":"naf7oq6lzdms","labelEn":"Management","parentId":null,"labelAr":"المصاريف الإدارية","isGroup":true},
  {"id":"e2bgaiyg5nv6","labelEn":"Management fees","parentId":"naf7oq6lzdms","labelAr":"","isGroup":false},
  {"id":"92bw8najcl6v","labelEn":"Subscription fees","parentId":"naf7oq6lzdms","labelAr":"","isGroup":false}
]

export const unitTypeOptions = [
	{ label: "", value: null },
	{ label: "شقة", value: "شقة" },
	{ label: "بيت", value: "بيت" },
	{ label: "فيلا", value: "فيلا" },
	{ label: "سرداب", value: "سرداب" },
	{ label: "محل", value: "محل" },
	{ label: "مخزن", value: "مخزن" },
	{ label: "شاليه", value: "شاليه" },
];
