import { randomUUID } from 'node:crypto';

// TODO: use this in all factories
export const TIMESPAN = 2;

const generateId = (): string => randomUUID();

export const areas: [string, string][] = [
	['Umm Al-Maradim Island', 'جزيرة أم المرادم'],
	['Auha Island', 'جزيرة عوهة'],
	['Mischan Island', 'جزيرة مسكان'],
	['Dasman', 'دسمان'],
	['Ardhiya Herafiya', 'العارضية الحرفية'],
	["Al Bida'a", 'البدع'],
	['Ministries Area', 'منطقة الوزارات'],
	['Nuzha', 'النزهة'],
	['Bnaid Al-Qar', 'بنيد القار'],
	['Qadsiya', 'القادسية'],
	['Nahda', 'النهضة'],
	['Dasma', 'الدسمة'],
	['Naeem', 'النعيم'],
	['Rehab', 'الرحاب'],
	['Yarmouk', 'اليرموك'],
	['Sulaibiya Industrial 1', 'الصليبية الصناعية 1'],
	['Omariya', 'العمرية'],
	['Shuwaikh Industrial-3', 'الشويخ الصناعية 3'],
	['Abdulla Al-Salem', 'ضاحية عبدالله السالم'],
	['Riggai', 'الرقعي'],
	['Adailiya', 'العديلية'],
	['Shuwaikh Industrial-2', 'الشويخ الصناعية 2'],
	['Sharq', 'شرق'],
	['West Abdullah Al-Mubarak', 'غرب عبدالله المبارك'],
	['Rawda', 'الروضة'],
	['Qibla', 'القبلة'],
	['Kifan', 'كيفان'],
	['Surra', 'السرة'],
	['Ghornata', 'غرناطة'],
	['Abu Hassaniah', 'أبو الحصانية'],
	['Northwest Sulaibikhat', 'شمال غرب الصليبيخات'],
	['Al Sour Gardens', 'حدائق السور'],
	['Shaab', 'الشعب'],
	['Al-Siddiq', 'الصديق'],
	['Hadiya', 'هدية'],
	['Shuwaikh', 'الشويخ'],
	['Rajim Khashman', 'رجم خشمان'],
	['Ardhiya 4', 'العارضية 4'],
	['Al-Fnaitees', 'ضاحية الفنيطيس'],
	['Farwaniya', 'الفروانية'],
	['Al-Qurain', 'القرين'],
	['Zahra', 'الزهراء'],
	['Al-Nuwaiseeb', 'النويصيب'],
	['Al-Qusour', 'القصور'],
	['Rumaithiya', 'الرميثية'],
	['Shalehat Al-Nuwaiseeb', 'شاليهات النويصيب'],
	['Mubarakiya Camps', 'معسكرات المباركية'],
	['Middle of Ahmadi', 'وسط الأحمدي'],
	['Janobyia Aljawakheer', 'الجنوبية الجواخير'],
	['Qasr', 'القصر'],
	['Al-Adan', 'العدان'],
	['Hawalli', 'حولي'],
	['Andalus', 'الأندلس'],
	['Sabah Al-Nasser', 'صباح الناصر'],
	['Health Area', 'المنطقة الصحية'],
	['East Ahmadi', 'شرق الأحمدي'],
	['Subhan Industrial', 'صبحان الصناعية'],
	['South Ahmadi', 'جنوب الأحمدي'],
	['Salwa', 'سلوى'],
	['Jleeb Al-Shiyoukh', 'جليب الشيوخ'],
	['Bayan', 'بيان'],
	['Sabah Al-Salem', 'صباح السالم'],
	['Jahra Industrial Herafiya 1', 'الجهراء الصناعية الحرفية 1'],
	["Shalehat Jlea'a", 'شاليهات الجليعة'],
	['Sabah Al-Salem University City', 'مدينة صباح السالم الجامعية'],
	['Al-Fintas', 'الفنطاس'],
	['South Al Mutlaa 2', 'جنوب المطلاع 2'],
	['Shuwaikh Industrial-1', 'الشويخ الصناعية 1'],
	['Shuaiba Industrial Western', 'الشعيبه الصناعيه الغربيه'],
	['Fahaheel', 'الفحيحيل'],
	['Mina Abdulla', 'ميناء عبدالله'],
	['Kabd', 'كبد'],
	['Shalehat Mina Abdullah', 'شاليهات ميناء عبدالله'],
	['Shuaiba Industrial esterly', 'الشعيبة الصناعية الشرقية'],
	['International Airport', 'المطار الدولي'],
	['South Al Mutlaa 4', 'جنوب المطلاع 4'],
	['Mina Al-Ahmadi Refinery', 'مصفاة ميناء الأحمدي'],
	['Failaka Island', 'جزيرة فيلكا'],
	['Zoor', 'الزور'],
	['Sabah Al-Ahmad 2', 'صباح الأحمد 2'],
	['Wista', 'المنطقة الوسطى'],
	['Sabah Al-Ahmad 4', 'صباح الأحمد 4'],
	['Sabah Al-Ahmad Investment', 'صباح الأحمد استثمارية'],
	['Umm Al-Aish', 'ام العيش'],
	['Sabah Al-Ahmad 3', 'صباح الأحمد 3'],
	['Sabah Al-Ahmad 5', 'صباح الأحمد 5'],
	['Rawdatain', 'الروضتين'],
	['Wafra', 'الوفرة'],
	['Al Masayel', 'المسايل'],
	['Salam', 'السلام'],
	['Sulaibikhat Cemetery', 'مقبرة الصليبيخات'],
	['Anjafa', 'أنجفة'],
	['South Al Mutlaa', 'جنوب المطلاع'],
	['South Al Mutlaa 5', 'جنوب المطلاع 5'],
	['South Al Mutlaa 7', 'جنوب المطلاع 7'],
	['South Al Mutlaa 9', 'جنوب المطلاع 9'],
	['South Al Mutlaa 12', 'جنوب المطلاع 12'],
	['Bar Al-Jahra Governorate', 'بر محافظة الجهراء'],
	['Ahmadi Governorate Desert', 'بر محافظة الأحمدي'],
	['Shalehat Al-Khiran', 'شاليهات الخيران'],
	['Qaruh Island', 'جزيرة قاروه'],
	['Kubbar Island', 'جزيرة كبر'],
	['Jawakher Al Jahra', 'جواخير الجهراء'],
	['Mubarakyia', 'المباركية'],
	['West Abu Ftirah Hirafyia', 'غرب أبو فطيرة الحرفية'],
	['Mansouriya', 'المنصورية'],
	['Ardhiya 6', 'العارضية 6'],
	['Faiha', 'الفيحاء'],
	['Dajeej', 'ضجيج الطائرات'],
	['Waha', 'الواحة'],
	['Mirqab', 'المرقاب'],
	['Shamiya', 'الشامية'],
	['Daiya', 'الدعية'],
	['Oyoun', 'العيون'],
	['Rabiya', 'الرابية'],
	['Shalehat Zoor', 'شاليهات الزور'],
	['Shuhada', 'الشهداء'],
	['South Amghara', 'جنوب أمغره'],
	['Khaldiya', 'الخالدية'],
	['Umm Al-Namel Island', 'جزيرة أم النمل'],
	['Khiran City', 'الخيران السكنية'],
	['Mubarak Al-Abdullah', 'مبارك العبدالله'],
	['Qortuba', 'قرطبة'],
	['Fahad Al-Ahmad', 'فهد الأحمد'],
	['North Ahmadi', 'شمال الأحمدي'],
	['Ali Subah Al-Salem', 'علي صباح السالم'],
	['Ashbeliah', 'أشبيلية'],
	['Dhaher', 'الظهر'],
	['South Al Mutlaa 11', 'جنوب المطلاع 11'],
	['Hitteen', 'حطين'],
	['Riqqa', 'الرقة'],
	['Ferdous', 'الفردوس'],
	['Jaber Al-Ali', 'ضاحية جابر العلي'],
	['Jahra', 'الجهراء'],
	['Messila', 'المسيلة'],
	['Nasseem', 'النسيم'],
	['Egaila', 'العقيلة'],
	['Abu Ftaira', 'ضاحية أبو فطيرة'],
	['Ardhiya', 'العارضية'],
	['South-Sabahiya', 'جنوب الصباحية'],
	['Al shadadyia Industrial', 'الشدادية الصناعية'],
	['The Sea Front', 'الواجهة البحرية'],
	['Abu Halifa', 'أبو حليفة'],
	['Taima', 'تيماء'],
	['Rai', 'الري'],
	['Jabriya', 'الجابرية'],
	['Mubarak Al-Kabeer', 'مبارك الكبير'],
	['Mishrif', 'مشرف'],
	['Kaerawan', 'القيروان'],
	['Sabahiya', 'الصباحية'],
	['Sulaibiya Industrial 2', 'الصليبية الصناعية 2'],
	['Sulaibiya', 'الصليبية الشعبية'],
	['Khaitan', 'خيطان'],
	['Mahboula', 'المهبولة'],
	['North West Jahra', 'شمال غرب الجهراء'],
	['Mangaf', 'المنقف'],
	['Mina Abdullah Refinery', 'مصفاة ميناء عبدالله'],
	['Doha', 'الدوحة'],
	['Shalehat Doha', 'شاليهات الدوحة'],
	['Sulaibyia Industrial 3', 'الصليبية الصناعية 3'],
	['Amghara Industrial', 'أمغرة الصناعية'],
	['Shuwaikh Port', 'المنطقة الحرة'],
	['Abdullah Mubarak Al-Sabah', 'عبدالله مبارك الصباح'],
	['Saad Al-Abdulla City', 'مدينة سعد العبدالله'],
	["Shalehat Dba'ayeh", 'شاليهات الضباعية'],
	['Jaber Al-Ahmad', 'جابر الأحمد'],
	['South Al Mutlaa 3', 'جنوب المطلاع 3'],
	['Warba Island', 'جزيرة وربة'],
	['Salmiya', 'السالمية'],
	['Magwa', 'المقوع'],
	['Al Naayem', 'النعايم'],
	['Abdally', 'العبدلي'],
	['Salmy', 'السالمي'],
	['Jahra Camps', 'معسكرات الجهراء'],
	['Sabah Al-Ahmad Services', 'صباح الأحمد الخدمية'],
	['Mina Doha', 'ميناء الدوحة'],
	['Shalehat Subiya', 'شاليهات الصبية'],
	['Bhaith', 'البحيث'],
	['Shalehat Bneder', 'شاليهات بنيدر'],
	['Sabah Al-Ahmad 6', 'صباح الأحمد 6'],
	['Shalehat Kazima', 'شاليهات كاظمة'],
	['Kazima', 'كاظمة'],
	['Sabah Al-Ahmad 1', 'صباح الأحمد 1'],
	['Subiya', 'الصبية'],
	['Bubyan Island', 'جزيرة بوبيان'],
	['Sulaibiya Agricultural', 'الصليبية الزراعية'],
	['New Wafra', 'الوفرة الجديدة'],
	['Wafra Farms', 'مزارع الوفرة'],
	['Sulaibikhat', 'الصليبيخات'],
	['Al Mutlaa', 'المطلاع'],
	['South Al Mutlaa 1', 'جنوب المطلاع 1'],
	['South Al Mutlaa 6', 'جنوب المطلاع 6'],
	['South Al Mutlaa 8', 'جنوب المطلاع 8'],
	['South Al Mutlaa 10', 'جنوب المطلاع 10'],
	['South Abdullah Al-Mubarak', 'جنوب عبدالله المبارك'],
	['Al Sheqaya', 'الشقايا'],
	['Sabah Al-Ahmad Al-marine', 'صباح الاحمد البحرية'],
	['kabd Agricultural', 'كبد الزراعية'],
];

export const coordinates: [number, number][] = [
	[29.14, 48.12],
	[29.12, 48.13],
	[29.09, 48.06],
	[29.26, 48.08],
	[29.15, 48.13],
	[28.88, 48.17],
	[29.08, 48.14],
	[29.17, 48.1],
	[29.09, 48.09],
	[29.1, 48.14],
	[29.24, 47.97],
	[29.19, 48.02],
	[29.17, 47.58],
	[29.2, 48.04],
	[29.28, 48.01],
	[29.24, 47.97],
	[29.24, 47.97],
	[29.24, 47.97],
	[29.27, 48.03],
	[29.34, 48.02],
	[29.34, 48.04],
	[29.27, 48.09],
	[29.28, 48.05],
	[29.34, 48.04],
	[29.33, 48.07],
	[29.19, 48.04],
	[29.3, 48.08],
	[29.34, 48.08],
	[29.35, 48.01],
	[29.33, 48.09],
	[29.35, 48.09],
	[29.34, 48.07],
	[29.32, 48.02],
	[29.34, 48.07],
	[29.28, 48.07],
	[29.27, 48.05],
	[29.29, 47.97],
	[29.35, 48.02],
	[29.34, 48.03],
	[29.33, 48.09],
	[29.34, 48.08],
	[29.34, 48.09],
	[29.32, 48.03],
	[29.33, 48.08],
	[29.34, 48.07],
	[29.36, 47.97],
	[29.29, 47.9],
	[29.35, 47.67],
	[29.34, 47.96],
	[29.33, 47.91],
	[29.19, 47.58],
	[29.19, 47.58],
	[29.19, 47.58],
	[29.33, 47.96],
	[29.38, 47.98],
	[29.21, 47.56],
	[29.33, 47.94],
	[29.32, 47.83],
	[29.12, 48.14],
	[29.38, 48],
	[29.37, 47.97],
	[29.34, 47.95],
	[29.34, 47.95],
	[29.32, 48.09],
	[29.24, 47.9],
	[29.17, 48.1],
	[29.32, 47.97],
	[29.3, 47.93],
	[29.38, 47.99],
	[29.37, 47.98],
	[29.33, 47.95],
	[29.3, 48.09],
	[29.39, 47.98],
	[29.3, 47.94],
	[29.39, 47.99],
	[28.88, 48.16],
	[29.3, 47.9],
	[29.36, 48.01],
	[29.34, 47.94],
	[29.21, 48.1],
	[29.32, 48.02],
	[29.38, 47.98],
	[28.73, 48.28],
	[29.3, 47.93],
	[29.36, 47.96],
	[29.2, 48.05],
	[29.3, 47.93],
	[29.3, 47.94],
	[29.3, 47.94],
	[29.36, 47.96],
	[28.89, 48.23],
	[29.33, 47.98],
	[28.88, 48.17],
	[29.25, 48.04],
	[29.36, 47.97],
	[29.37, 47.97],
	[29.3, 47.94],
	[29.3, 47.93],
	[29.38, 47.98],
	[29.37, 47.98],
	[29.3, 47.93],
	[29.11, 48.06],
	[29.17, 48.06],
	[29.24, 48.09],
	[29.19, 48.09],
	[29.2, 48.09],
];

export type Tree = ReturnType<typeof generateExpenseCategoryTree>;

/**
 * Returns a default expense category tree with random ids.
 */
export const generateExpenseCategoryTree = () => {
	const mappedIds = new Map<string, string>();

	defaultExpenseCategoryTree.forEach((category) => {
		mappedIds.set(category.id, generateId());
	});

	const withRandomIds = defaultExpenseCategoryTree.map((category) => {
		const newId = mappedIds.get(category.id);
		const newParentId = category.parentId
			? mappedIds.get(category.parentId)
			: null;
		return {
			...category,
			id: newId ?? generateId(),
			parentId: newParentId || null,
		};
	});

	return withRandomIds;
};

/**
 * Generate a random id for both the `id` and `parentId` fields.
 */
// prettier-ignore
const defaultExpenseCategoryTree = [
  {"id":"1","labelAr":"المصاريف الرأسمالية","labelEn":"CapEx","parentId":null,"isGroup":true},
  {"id":"2","labelAr":"عقود الصيانة السنوية","labelEn":"Annual Contracts","parentId":"1","isGroup":true},
  {"id":"3","labelAr":"","labelEn":"AC Contract","parentId":"2","isGroup":false},
  {"id":"4","labelAr":"","labelEn":"Elevator Contract","parentId":"2","isGroup":false},
  {"id":"5","labelAr":"","labelEn":"Fire Fighting Contract","parentId":"2","isGroup":false},
  {"id":"6","labelAr":"","labelEn":"Other CapEx","parentId":"1","isGroup":true},
  {"id":"7","labelAr":"","labelEn":"Waterproofing","parentId":"6","isGroup":false},
  {"id":"8","labelAr":"","labelEn":"Renovation","parentId":"6","isGroup":false},
  {"id":"9","labelAr":"","labelEn":"Major repairs","parentId":"6","isGroup":false},
  {"id":"10","labelAr":"","labelEn":"Structural Integrity","parentId":"6","isGroup":false},
  {"id":"11","labelAr":"المصاريف التشغيلية","labelEn":"OpEx","parentId":null,"isGroup":true},
  {"id":"12","labelAr":"المصاريف القانونية","labelEn":"Legal & Financial","parentId":"11","isGroup":true},
  {"id":"13","labelAr":"","labelEn":"Attorneys Fee","parentId":"12","isGroup":false},
  {"id":"14","labelAr":"","labelEn":"Insurance","parentId":"12","isGroup":false},
  {"id":"15","labelAr":"","labelEn":"Bank charges","parentId":"12","isGroup":false},
  {"id":"16","labelAr":"المصاريف الحكومية","labelEn":"Government","parentId":"11","isGroup":true},
  {"id":"17","labelAr":"","labelEn":"Municipal fees","parentId":"16","isGroup":false},
  {"id":"18","labelAr":"","labelEn":"Government Stamps","parentId":"16","isGroup":false},
  {"id":"19","labelAr":"","labelEn":"Government Paperwork","parentId":"16","isGroup":false},
  {"id":"20","labelAr":"","labelEn":"Government Violations","parentId":"16","isGroup":false},
  {"id":"21","labelAr":"رواتب الحارس","labelEn":"Salaries","parentId":"11","isGroup":true},
  {"id":"22","labelAr":"","labelEn":"Caretaker Wages","parentId":"21","isGroup":false},
  {"id":"23","labelAr":"","labelEn":"Caretaker Vacation leave","parentId":"21","isGroup":false},
  {"id":"24","labelAr":"","labelEn":"Caretaker pension","parentId":"21","isGroup":false},
  {"id":"25","labelAr":"","labelEn":"Caretaker Insurance & resident permit","parentId":"21","isGroup":false},
  {"id":"26","labelAr":"خدمات الكهرباء والماء","labelEn":"Utilities","parentId":"11","isGroup":true},
  {"id":"27","labelAr":"","labelEn":"Water Consumption","parentId":"26","isGroup":false},
  {"id":"28","labelAr":"","labelEn":"Electrical Consumption","parentId":"26","isGroup":false},
  {"id":"29","labelAr":"","labelEn":"Gas","parentId":"26","isGroup":false},
  {"id":"30","labelAr":"","labelEn":"Trash","parentId":"26","isGroup":false},
  {"id":"31","labelAr":"خدمات الإصلاحات","labelEn":"Repairs","parentId":"11","isGroup":true},
  {"id":"32","labelAr":"","labelEn":"Central Ventilation","parentId":"31","isGroup":false},
  {"id":"33","labelAr":"","labelEn":"Paint repairs","parentId":"31","isGroup":false},
  {"id":"34","labelAr":"","labelEn":"Doors repairs","parentId":"31","isGroup":false},
  {"id":"35","labelAr":"","labelEn":"Glass repairs","parentId":"31","isGroup":false},
  {"id":"36","labelAr":"","labelEn":"Aluminum repairs","parentId":"31","isGroup":false},
  {"id":"37","labelAr":"","labelEn":"Plasterwork repairs","parentId":"31","isGroup":false},
  {"id":"38","labelAr":"","labelEn":"Electrical repairs","parentId":"31","isGroup":false},
  {"id":"39","labelAr":"","labelEn":"Plumbing repairs","parentId":"31","isGroup":false},
  {"id":"40","labelAr":"","labelEn":"Gypsum repairs","parentId":"31","isGroup":false},
  {"id":"41","labelAr":"خدمات الصيانة","labelEn":"Maintenance","parentId":"11","isGroup":true},
  {"id":"42","labelAr":"","labelEn":"Property Maintenance","parentId":"41","isGroup":false},
  {"id":"43","labelAr":"","labelEn":"Amenities Maintenance","parentId":"41","isGroup":false},
  {"id":"44","labelAr":"","labelEn":"Apartment Maintenance","parentId":"41","isGroup":false},
  {"id":"45","labelAr":"","labelEn":"AC Maintenance","parentId":"41","isGroup":false},
  {"id":"46","labelAr":"","labelEn":"Elevator Maintenance","parentId":"41","isGroup":false},
  {"id":"47","labelAr":"","labelEn":"Electrical Maintenance","parentId":"41","isGroup":false},
  {"id":"48","labelAr":"","labelEn":"Plumbing maintenance","parentId":"41","isGroup":false},
  {"id":"49","labelAr":"المصاريف الإدارية","labelEn":"Management","parentId":null,"isGroup":true},
  {"id":"50","labelAr":"","labelEn":"Management fees","parentId":"49","isGroup":false},
  {"id":"51","labelAr":"","labelEn":"Subscription fees","parentId":"49","isGroup":false}
]

export const unitTypeOptions = [
	{ label: '', value: null },
	{ label: 'شقة', value: 'شقة' },
	{ label: 'بيت', value: 'بيت' },
	{ label: 'فيلا', value: 'فيلا' },
	{ label: 'سرداب', value: 'سرداب' },
	{ label: 'محل', value: 'محل' },
	{ label: 'مخزن', value: 'مخزن' },
	{ label: 'شاليه', value: 'شاليه' },
];
