# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: '3'

interval: '300ms'

dotenv: ['../../.env']

tasks:
  clean:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - rm -rf dist

  build:utils:
    dir: '{{.USER_WORKING_DIR}}'
    method: none
    sources:
      - ../utils/src/**/*.ts
    cmds:
      - pnpm swc -d dist ../utils/src

  build:backend:
    dir: '{{.USER_WORKING_DIR}}'
    method: none
    sources:
      - src/**/*.ts
    cmds:
      - pnpm swc -d dist/backend/src src
      - cp package.json dist/backend

  build:
    dir: '{{.USER_WORKING_DIR}}'
    method: none
    cmds:
      - task: clean
      - task: build:utils
      - task: build:backend

  start:prod:
    dir: '{{.USER_WORKING_DIR}}'
    method: none
    deps:
      - build
    cmds:
      - node dist/backend/src/main.js

  start:mock:
    dir: '{{.USER_WORKING_DIR}}'
    method: none
    deps:
      - build
    cmds:
      - pnpm vitest --run mocked.spec.ts -c vitest.config.mocked.ts

  start:
    # Detect start mode based on PUBLIC_IS_TESTING from .env
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: '{{if eq .PUBLIC_IS_TESTING "1"}}start:mock{{else}}start:prod{{end}}'
