/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech API
 * The Aqratech API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CombinedEnum,
  CreatePropertyDto,
  PaginatedPropertyDto,
  PaginatedUnitDto,
  PropertyDto,
  SortOrderEnum,
  UpdatePropertyDto,
} from '../models';

export interface PropertiesApiCreateRequest {
    createPropertyDto: CreatePropertyDto;
    xRoleId?: string;
}

export interface PropertiesApiFindAllRequest {
    xRoleId?: string;
    page?: number;
    take?: number;
    orderBy?: CombinedEnum;
    sortOrder?: SortOrderEnum;
    filter?: object;
}

export interface PropertiesApiFindOneRequest {
    id: string;
    xRoleId?: string;
}

export interface PropertiesApiFindUnitsRequest {
    id: string;
    xRoleId?: string;
    page?: number;
    take?: number;
    orderBy?: CombinedEnum;
    sortOrder?: SortOrderEnum;
    filter?: object;
}

export interface PropertiesApiRemoveRequest {
    id: string;
    xRoleId?: string;
}

export interface PropertiesApiUpdateRequest {
    id: string;
    updatePropertyDto: UpdatePropertyDto;
    xRoleId?: string;
}

/**
 * PropertiesApi - interface
 * 
 * @export
 * @interface PropertiesApiInterface
 */
export interface PropertiesApiInterface {
    /**
     * 
     * @summary 
     * @param {CreatePropertyDto} createPropertyDto 
     * @param {string} [xRoleId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropertiesApiInterface
     */
    createRaw(requestParameters: PropertiesApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropertyDto>>;

    /**
     * 
     * 
     */
    create(requestParameters: PropertiesApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropertyDto>;

    /**
     * 
     * @summary 
     * @param {string} [xRoleId] 
     * @param {number} [page] 
     * @param {number} [take] 
     * @param {CombinedEnum} [orderBy] 
     * @param {SortOrderEnum} [sortOrder] 
     * @param {object} [filter] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropertiesApiInterface
     */
    findAllRaw(requestParameters: PropertiesApiFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedPropertyDto>>;

    /**
     * 
     * 
     */
    findAll(requestParameters: PropertiesApiFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedPropertyDto>;

    /**
     * 
     * @summary 
     * @param {string} id 
     * @param {string} [xRoleId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropertiesApiInterface
     */
    findOneRaw(requestParameters: PropertiesApiFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropertyDto>>;

    /**
     * 
     * 
     */
    findOne(requestParameters: PropertiesApiFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropertyDto>;

    /**
     * 
     * @summary 
     * @param {string} id 
     * @param {string} [xRoleId] 
     * @param {number} [page] 
     * @param {number} [take] 
     * @param {CombinedEnum} [orderBy] 
     * @param {SortOrderEnum} [sortOrder] 
     * @param {object} [filter] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropertiesApiInterface
     */
    findUnitsRaw(requestParameters: PropertiesApiFindUnitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedUnitDto>>;

    /**
     * 
     * 
     */
    findUnits(requestParameters: PropertiesApiFindUnitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedUnitDto>;

    /**
     * 
     * @summary 
     * @param {string} id 
     * @param {string} [xRoleId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropertiesApiInterface
     */
    removeRaw(requestParameters: PropertiesApiRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * 
     * 
     */
    remove(requestParameters: PropertiesApiRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * 
     * @summary 
     * @param {string} id 
     * @param {UpdatePropertyDto} updatePropertyDto 
     * @param {string} [xRoleId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PropertiesApiInterface
     */
    updateRaw(requestParameters: PropertiesApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropertyDto>>;

    /**
     * 
     * 
     */
    update(requestParameters: PropertiesApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropertyDto>;

}

/**
 * 
 */
export class PropertiesApi extends runtime.BaseAPI implements PropertiesApiInterface {

    /**
     * 
     * 
     */
    async createRaw(requestParameters: PropertiesApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropertyDto>> {
        if (requestParameters.createPropertyDto === null || requestParameters.createPropertyDto === undefined) {
            throw new runtime.RequiredError('createPropertyDto','Required parameter requestParameters.createPropertyDto was null or undefined when calling create.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xRoleId !== undefined && requestParameters.xRoleId !== null) {
            headerParameters['x-role-id'] = String(requestParameters.xRoleId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth-swagger", []);
        }

        const response = await this.request({
            path: `/properties`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.createPropertyDto,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 
     * 
     */
    async create(requestParameters: PropertiesApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropertyDto> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 
     */
    async findAllRaw(requestParameters: PropertiesApiFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedPropertyDto>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.take !== undefined) {
            queryParameters['take'] = requestParameters.take;
        }

        if (requestParameters.orderBy !== undefined) {
            queryParameters['orderBy'] = requestParameters.orderBy;
        }

        if (requestParameters.sortOrder !== undefined) {
            queryParameters['sortOrder'] = requestParameters.sortOrder;
        }

        if (requestParameters.filter !== undefined) {
            queryParameters['filter'] = requestParameters.filter;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xRoleId !== undefined && requestParameters.xRoleId !== null) {
            headerParameters['x-role-id'] = String(requestParameters.xRoleId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth-swagger", []);
        }

        const response = await this.request({
            path: `/properties`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 
     * 
     */
    async findAll(requestParameters: PropertiesApiFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedPropertyDto> {
        const response = await this.findAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 
     */
    async findOneRaw(requestParameters: PropertiesApiFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropertyDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xRoleId !== undefined && requestParameters.xRoleId !== null) {
            headerParameters['x-role-id'] = String(requestParameters.xRoleId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth-swagger", []);
        }

        const response = await this.request({
            path: `/properties/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 
     * 
     */
    async findOne(requestParameters: PropertiesApiFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropertyDto> {
        const response = await this.findOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 
     */
    async findUnitsRaw(requestParameters: PropertiesApiFindUnitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedUnitDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findUnits.');
        }

        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.take !== undefined) {
            queryParameters['take'] = requestParameters.take;
        }

        if (requestParameters.orderBy !== undefined) {
            queryParameters['orderBy'] = requestParameters.orderBy;
        }

        if (requestParameters.sortOrder !== undefined) {
            queryParameters['sortOrder'] = requestParameters.sortOrder;
        }

        if (requestParameters.filter !== undefined) {
            queryParameters['filter'] = requestParameters.filter;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xRoleId !== undefined && requestParameters.xRoleId !== null) {
            headerParameters['x-role-id'] = String(requestParameters.xRoleId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth-swagger", []);
        }

        const response = await this.request({
            path: `/properties/{id}/units`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 
     * 
     */
    async findUnits(requestParameters: PropertiesApiFindUnitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedUnitDto> {
        const response = await this.findUnitsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 
     */
    async removeRaw(requestParameters: PropertiesApiRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling remove.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xRoleId !== undefined && requestParameters.xRoleId !== null) {
            headerParameters['x-role-id'] = String(requestParameters.xRoleId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth-swagger", []);
        }

        const response = await this.request({
            path: `/properties/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * 
     * 
     */
    async remove(requestParameters: PropertiesApiRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.removeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 
     */
    async updateRaw(requestParameters: PropertiesApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropertyDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling update.');
        }

        if (requestParameters.updatePropertyDto === null || requestParameters.updatePropertyDto === undefined) {
            throw new runtime.RequiredError('updatePropertyDto','Required parameter requestParameters.updatePropertyDto was null or undefined when calling update.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xRoleId !== undefined && requestParameters.xRoleId !== null) {
            headerParameters['x-role-id'] = String(requestParameters.xRoleId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth-swagger", []);
        }

        const response = await this.request({
            path: `/properties/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.updatePropertyDto,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 
     * 
     */
    async update(requestParameters: PropertiesApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropertyDto> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
