/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech
 * Aqaratech API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
	CreateExpenseCategoryDto,
	ExpenseCategoryDto,
	UpdateExpenseCategoryDto,
	UpdateExpenseCategoryTreeDto,
} from '../models';

export interface ExpenseCategoriesApiCreateRequest {
	organizationId: string;
	createExpenseCategoryDto: CreateExpenseCategoryDto;
}

export interface ExpenseCategoriesApiFindAllRequest {
	organizationId: string;
}

export interface ExpenseCategoriesApiUpdateRequest {
	organizationId: string;
	id: string;
	updateExpenseCategoryDto: UpdateExpenseCategoryDto;
}

export interface ExpenseCategoriesApiUpdateAllRequest {
	organizationId: string;
	updateExpenseCategoryTreeDto: Array<UpdateExpenseCategoryTreeDto>;
}

/**
 *
 */
export class ExpenseCategoriesApi extends runtime.BaseAPI {
	/**
	 */
	async createRaw(
		requestParameters: ExpenseCategoriesApiCreateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<ExpenseCategoryDto>> {
		if (
			requestParameters.organizationId === null ||
			requestParameters.organizationId === undefined
		) {
			throw new runtime.RequiredError(
				'organizationId',
				'Required parameter requestParameters.organizationId was null or undefined when calling create.',
			);
		}

		if (
			requestParameters.createExpenseCategoryDto === null ||
			requestParameters.createExpenseCategoryDto === undefined
		) {
			throw new runtime.RequiredError(
				'createExpenseCategoryDto',
				'Required parameter requestParameters.createExpenseCategoryDto was null or undefined when calling create.',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		const response = await this.request(
			{
				path: `/organizations/{organizationId}/expense-categories`.replace(
					`{${'organizationId'}}`,
					encodeURIComponent(String(requestParameters.organizationId)),
				),
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: requestParameters.createExpenseCategoryDto,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response);
	}

	/**
	 */
	async create(
		requestParameters: ExpenseCategoriesApiCreateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<ExpenseCategoryDto> {
		const response = await this.createRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async findAllRaw(
		requestParameters: ExpenseCategoriesApiFindAllRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<Array<ExpenseCategoryDto>>> {
		if (
			requestParameters.organizationId === null ||
			requestParameters.organizationId === undefined
		) {
			throw new runtime.RequiredError(
				'organizationId',
				'Required parameter requestParameters.organizationId was null or undefined when calling findAll.',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		const response = await this.request(
			{
				path: `/organizations/{organizationId}/expense-categories`.replace(
					`{${'organizationId'}}`,
					encodeURIComponent(String(requestParameters.organizationId)),
				),
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response);
	}

	/**
	 */
	async findAll(
		requestParameters: ExpenseCategoriesApiFindAllRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<Array<ExpenseCategoryDto>> {
		const response = await this.findAllRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async updateRaw(
		requestParameters: ExpenseCategoriesApiUpdateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<ExpenseCategoryDto>> {
		if (
			requestParameters.organizationId === null ||
			requestParameters.organizationId === undefined
		) {
			throw new runtime.RequiredError(
				'organizationId',
				'Required parameter requestParameters.organizationId was null or undefined when calling update.',
			);
		}

		if (requestParameters.id === null || requestParameters.id === undefined) {
			throw new runtime.RequiredError(
				'id',
				'Required parameter requestParameters.id was null or undefined when calling update.',
			);
		}

		if (
			requestParameters.updateExpenseCategoryDto === null ||
			requestParameters.updateExpenseCategoryDto === undefined
		) {
			throw new runtime.RequiredError(
				'updateExpenseCategoryDto',
				'Required parameter requestParameters.updateExpenseCategoryDto was null or undefined when calling update.',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		const response = await this.request(
			{
				path: `/organizations/{organizationId}/expense-categories/{id}`
					.replace(
						`{${'organizationId'}}`,
						encodeURIComponent(String(requestParameters.organizationId)),
					)
					.replace(
						`{${'id'}}`,
						encodeURIComponent(String(requestParameters.id)),
					),
				method: 'PATCH',
				headers: headerParameters,
				query: queryParameters,
				body: requestParameters.updateExpenseCategoryDto,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response);
	}

	/**
	 */
	async update(
		requestParameters: ExpenseCategoriesApiUpdateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<ExpenseCategoryDto> {
		const response = await this.updateRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 */
	async updateAllRaw(
		requestParameters: ExpenseCategoriesApiUpdateAllRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<Array<ExpenseCategoryDto>>> {
		if (
			requestParameters.organizationId === null ||
			requestParameters.organizationId === undefined
		) {
			throw new runtime.RequiredError(
				'organizationId',
				'Required parameter requestParameters.organizationId was null or undefined when calling updateAll.',
			);
		}

		if (
			requestParameters.updateExpenseCategoryTreeDto === null ||
			requestParameters.updateExpenseCategoryTreeDto === undefined
		) {
			throw new runtime.RequiredError(
				'updateExpenseCategoryTreeDto',
				'Required parameter requestParameters.updateExpenseCategoryTreeDto was null or undefined when calling updateAll.',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		const response = await this.request(
			{
				path: `/organizations/{organizationId}/expense-categories`.replace(
					`{${'organizationId'}}`,
					encodeURIComponent(String(requestParameters.organizationId)),
				),
				method: 'PATCH',
				headers: headerParameters,
				query: queryParameters,
				body: requestParameters.updateExpenseCategoryTreeDto,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response);
	}

	/**
	 */
	async updateAll(
		requestParameters: ExpenseCategoriesApiUpdateAllRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<Array<ExpenseCategoryDto>> {
		const response = await this.updateAllRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
