/* tslint:disable */
/* eslint-disable */
/**
 * Aqaratech
 * Aqaratech API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
	CreateLeaseDto,
	CreateManyLeaseInvoicesDto,
	LeaseDto,
	PaginatedLeaseDto,
	PaginatedLeaseInvoiceDto,
	PaidStatusEnum,
	PartialLeaseDto,
	SortOrderEnum,
	UpdateLeaseDto,
} from '../models';

export interface LeasesApiCreateRequest {
	createLeaseDto: CreateLeaseDto;
}

export interface LeasesApiCreateInvoicesRequest {
	id: string;
	createManyLeaseInvoicesDto: Array<CreateManyLeaseInvoicesDto>;
}

export interface LeasesApiFindAllRequest {
	page?: number;
	take?: number;
	sortOrder?: SortOrderEnum;
	filter?: object;
	orderBy?: FindAllOrderByEnum;
}

export interface LeasesApiFindInvoicesRequest {
	id: string;
	page?: number;
	take?: number;
	sortOrder?: SortOrderEnum;
	filter?: object;
	start?: string;
	end?: string;
	paidStatus?: PaidStatusEnum;
	orderBy?: string;
	portfolioId?: string;
	propertyId?: string;
	unitId?: string;
}

export interface LeasesApiFindOneRequest {
	id: string;
}

export interface LeasesApiRemoveRequest {
	id: string;
}

export interface LeasesApiUpdateRequest {
	id: string;
	updateLeaseDto: UpdateLeaseDto;
}

/**
 * LeasesApi - interface
 *
 * @export
 * @interface LeasesApiInterface
 */
export interface LeasesApiInterface {
	/**
	 *
	 * @summary
	 * @param {CreateLeaseDto} createLeaseDto
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof LeasesApiInterface
	 */
	createRaw(
		requestParameters: LeasesApiCreateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PartialLeaseDto>>;

	/**
	 *
	 *
	 */
	create(
		requestParameters: LeasesApiCreateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PartialLeaseDto>;

	/**
	 *
	 * @summary
	 * @param {string} id
	 * @param {Array<CreateManyLeaseInvoicesDto>} createManyLeaseInvoicesDto
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof LeasesApiInterface
	 */
	createInvoicesRaw(
		requestParameters: LeasesApiCreateInvoicesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<string>>;

	/**
	 *
	 *
	 */
	createInvoices(
		requestParameters: LeasesApiCreateInvoicesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<string>;

	/**
	 *
	 * @summary
	 * @param {number} [page]
	 * @param {number} [take]
	 * @param {SortOrderEnum} [sortOrder]
	 * @param {object} [filter]
	 * @param {'id' | 'tenantId' | 'unitId' | 'createdAt' | 'updatedAt' | 'start' | 'end' | 'monthlyRent' | 'deposit' | 'canPay' | 'notify' | 'license' | 'organizationId' | 'portfolioId'} [orderBy]
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof LeasesApiInterface
	 */
	findAllRaw(
		requestParameters: LeasesApiFindAllRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PaginatedLeaseDto>>;

	/**
	 *
	 *
	 */
	findAll(
		requestParameters: LeasesApiFindAllRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PaginatedLeaseDto>;

	/**
	 *
	 * @summary
	 * @param {string} id
	 * @param {number} [page]
	 * @param {number} [take]
	 * @param {SortOrderEnum} [sortOrder]
	 * @param {object} [filter]
	 * @param {string} [start]
	 * @param {string} [end]
	 * @param {PaidStatusEnum} [paidStatus]
	 * @param {string} [orderBy]
	 * @param {string} [portfolioId]
	 * @param {string} [propertyId]
	 * @param {string} [unitId]
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof LeasesApiInterface
	 */
	findInvoicesRaw(
		requestParameters: LeasesApiFindInvoicesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PaginatedLeaseInvoiceDto>>;

	/**
	 *
	 *
	 */
	findInvoices(
		requestParameters: LeasesApiFindInvoicesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PaginatedLeaseInvoiceDto>;

	/**
	 *
	 * @summary
	 * @param {string} id
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof LeasesApiInterface
	 */
	findOneRaw(
		requestParameters: LeasesApiFindOneRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<LeaseDto>>;

	/**
	 *
	 *
	 */
	findOne(
		requestParameters: LeasesApiFindOneRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<LeaseDto>;

	/**
	 *
	 * @summary
	 * @param {string} id
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof LeasesApiInterface
	 */
	removeRaw(
		requestParameters: LeasesApiRemoveRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<string>>;

	/**
	 *
	 *
	 */
	remove(
		requestParameters: LeasesApiRemoveRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<string>;

	/**
	 *
	 * @summary
	 * @param {string} id
	 * @param {UpdateLeaseDto} updateLeaseDto
	 * @param {*} [options] Override http request option.
	 * @throws {RequiredError}
	 * @memberof LeasesApiInterface
	 */
	updateRaw(
		requestParameters: LeasesApiUpdateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PartialLeaseDto>>;

	/**
	 *
	 *
	 */
	update(
		requestParameters: LeasesApiUpdateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PartialLeaseDto>;
}

/**
 *
 */
export class LeasesApi extends runtime.BaseAPI implements LeasesApiInterface {
	/**
	 *
	 *
	 */
	async createRaw(
		requestParameters: LeasesApiCreateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PartialLeaseDto>> {
		if (
			requestParameters.createLeaseDto === null ||
			requestParameters.createLeaseDto === undefined
		) {
			throw new runtime.RequiredError(
				'createLeaseDto',
				'Required parameter requestParameters.createLeaseDto was null or undefined when calling create.',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('bearer', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}
		const response = await this.request(
			{
				path: `/leases`,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: requestParameters.createLeaseDto,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response);
	}

	/**
	 *
	 *
	 */
	async create(
		requestParameters: LeasesApiCreateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PartialLeaseDto> {
		const response = await this.createRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 *
	 *
	 */
	async createInvoicesRaw(
		requestParameters: LeasesApiCreateInvoicesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<string>> {
		if (requestParameters.id === null || requestParameters.id === undefined) {
			throw new runtime.RequiredError(
				'id',
				'Required parameter requestParameters.id was null or undefined when calling createInvoices.',
			);
		}

		if (
			requestParameters.createManyLeaseInvoicesDto === null ||
			requestParameters.createManyLeaseInvoicesDto === undefined
		) {
			throw new runtime.RequiredError(
				'createManyLeaseInvoicesDto',
				'Required parameter requestParameters.createManyLeaseInvoicesDto was null or undefined when calling createInvoices.',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('bearer', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}
		const response = await this.request(
			{
				path: `/leases/{id}/invoices`.replace(
					`{${'id'}}`,
					encodeURIComponent(String(requestParameters.id)),
				),
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: requestParameters.createManyLeaseInvoicesDto,
			},
			initOverrides,
		);

		return new runtime.TextApiResponse(response) as any;
	}

	/**
	 *
	 *
	 */
	async createInvoices(
		requestParameters: LeasesApiCreateInvoicesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<string> {
		const response = await this.createInvoicesRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 *
	 *
	 */
	async findAllRaw(
		requestParameters: LeasesApiFindAllRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PaginatedLeaseDto>> {
		const queryParameters: any = {};

		if (requestParameters.page !== undefined) {
			queryParameters['page'] = requestParameters.page;
		}

		if (requestParameters.take !== undefined) {
			queryParameters['take'] = requestParameters.take;
		}

		if (requestParameters.sortOrder !== undefined) {
			queryParameters['sortOrder'] = requestParameters.sortOrder;
		}

		if (requestParameters.filter !== undefined) {
			queryParameters['filter'] = requestParameters.filter;
		}

		if (requestParameters.orderBy !== undefined) {
			queryParameters['orderBy'] = requestParameters.orderBy;
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('bearer', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}
		const response = await this.request(
			{
				path: `/leases`,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response);
	}

	/**
	 *
	 *
	 */
	async findAll(
		requestParameters: LeasesApiFindAllRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PaginatedLeaseDto> {
		const response = await this.findAllRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 *
	 *
	 */
	async findInvoicesRaw(
		requestParameters: LeasesApiFindInvoicesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PaginatedLeaseInvoiceDto>> {
		if (requestParameters.id === null || requestParameters.id === undefined) {
			throw new runtime.RequiredError(
				'id',
				'Required parameter requestParameters.id was null or undefined when calling findInvoices.',
			);
		}

		const queryParameters: any = {};

		if (requestParameters.page !== undefined) {
			queryParameters['page'] = requestParameters.page;
		}

		if (requestParameters.take !== undefined) {
			queryParameters['take'] = requestParameters.take;
		}

		if (requestParameters.sortOrder !== undefined) {
			queryParameters['sortOrder'] = requestParameters.sortOrder;
		}

		if (requestParameters.filter !== undefined) {
			queryParameters['filter'] = requestParameters.filter;
		}

		if (requestParameters.start !== undefined) {
			queryParameters['start'] = requestParameters.start;
		}

		if (requestParameters.end !== undefined) {
			queryParameters['end'] = requestParameters.end;
		}

		if (requestParameters.paidStatus !== undefined) {
			queryParameters['paidStatus'] = requestParameters.paidStatus;
		}

		if (requestParameters.orderBy !== undefined) {
			queryParameters['orderBy'] = requestParameters.orderBy;
		}

		if (requestParameters.portfolioId !== undefined) {
			queryParameters['portfolioId'] = requestParameters.portfolioId;
		}

		if (requestParameters.propertyId !== undefined) {
			queryParameters['propertyId'] = requestParameters.propertyId;
		}

		if (requestParameters.unitId !== undefined) {
			queryParameters['unitId'] = requestParameters.unitId;
		}

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('bearer', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}
		const response = await this.request(
			{
				path: `/leases/{id}/invoices`.replace(
					`{${'id'}}`,
					encodeURIComponent(String(requestParameters.id)),
				),
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response);
	}

	/**
	 *
	 *
	 */
	async findInvoices(
		requestParameters: LeasesApiFindInvoicesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PaginatedLeaseInvoiceDto> {
		const response = await this.findInvoicesRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 *
	 *
	 */
	async findOneRaw(
		requestParameters: LeasesApiFindOneRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<LeaseDto>> {
		if (requestParameters.id === null || requestParameters.id === undefined) {
			throw new runtime.RequiredError(
				'id',
				'Required parameter requestParameters.id was null or undefined when calling findOne.',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('bearer', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}
		const response = await this.request(
			{
				path: `/leases/{id}`.replace(
					`{${'id'}}`,
					encodeURIComponent(String(requestParameters.id)),
				),
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response);
	}

	/**
	 *
	 *
	 */
	async findOne(
		requestParameters: LeasesApiFindOneRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<LeaseDto> {
		const response = await this.findOneRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 *
	 *
	 */
	async removeRaw(
		requestParameters: LeasesApiRemoveRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<string>> {
		if (requestParameters.id === null || requestParameters.id === undefined) {
			throw new runtime.RequiredError(
				'id',
				'Required parameter requestParameters.id was null or undefined when calling remove.',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('bearer', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}
		const response = await this.request(
			{
				path: `/leases/{id}`.replace(
					`{${'id'}}`,
					encodeURIComponent(String(requestParameters.id)),
				),
				method: 'DELETE',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.TextApiResponse(response) as any;
	}

	/**
	 *
	 *
	 */
	async remove(
		requestParameters: LeasesApiRemoveRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<string> {
		const response = await this.removeRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 *
	 *
	 */
	async updateRaw(
		requestParameters: LeasesApiUpdateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<PartialLeaseDto>> {
		if (requestParameters.id === null || requestParameters.id === undefined) {
			throw new runtime.RequiredError(
				'id',
				'Required parameter requestParameters.id was null or undefined when calling update.',
			);
		}

		if (
			requestParameters.updateLeaseDto === null ||
			requestParameters.updateLeaseDto === undefined
		) {
			throw new runtime.RequiredError(
				'updateLeaseDto',
				'Required parameter requestParameters.updateLeaseDto was null or undefined when calling update.',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('bearer', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}
		const response = await this.request(
			{
				path: `/leases/{id}`.replace(
					`{${'id'}}`,
					encodeURIComponent(String(requestParameters.id)),
				),
				method: 'PATCH',
				headers: headerParameters,
				query: queryParameters,
				body: requestParameters.updateLeaseDto,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response);
	}

	/**
	 *
	 *
	 */
	async update(
		requestParameters: LeasesApiUpdateRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<PartialLeaseDto> {
		const response = await this.updateRaw(requestParameters, initOverrides);
		return await response.value();
	}
}

/**
 * @export
 */
export const FindAllOrderByEnum = {
	Id: 'id',
	TenantId: 'tenantId',
	UnitId: 'unitId',
	CreatedAt: 'createdAt',
	UpdatedAt: 'updatedAt',
	Start: 'start',
	End: 'end',
	MonthlyRent: 'monthlyRent',
	Deposit: 'deposit',
	CanPay: 'canPay',
	Notify: 'notify',
	License: 'license',
	OrganizationId: 'organizationId',
	PortfolioId: 'portfolioId',
} as const;
export type FindAllOrderByEnum =
	typeof FindAllOrderByEnum[keyof typeof FindAllOrderByEnum];
