// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	entity: {
		user: {
			/**
			 * U​s​e​r​s
			 */
			plural: string
			/**
			 * U​s​e​r
			 */
			singular: string
		}
		organization: {
			/**
			 * O​r​g​a​n​i​z​a​t​i​o​n​s
			 */
			plural: string
			/**
			 * O​r​g​a​n​i​z​a​t​i​o​n
			 */
			singular: string
		}
		role: {
			/**
			 * R​o​l​e​s
			 */
			plural: string
			/**
			 * R​o​l​e
			 */
			singular: string
		}
		tenant: {
			/**
			 * T​e​n​a​n​t​s
			 */
			plural: string
			/**
			 * T​e​n​a​n​t
			 */
			singular: string
		}
		portfolio: {
			/**
			 * O​w​n​e​r​s
			 */
			plural: string
			/**
			 * O​w​n​e​r
			 */
			singular: string
		}
		property: {
			/**
			 * P​r​o​p​e​r​t​i​e​s
			 */
			plural: string
			/**
			 * P​r​o​p​e​r​t​y
			 */
			singular: string
		}
		unit: {
			/**
			 * U​n​i​t​s
			 */
			plural: string
			/**
			 * U​n​i​t
			 */
			singular: string
		}
		lease: {
			/**
			 * L​e​a​s​e​s
			 */
			plural: string
			/**
			 * L​e​a​s​e
			 */
			singular: string
		}
		leaseInvoice: {
			/**
			 * I​n​v​o​i​c​e​s
			 */
			plural: string
			/**
			 * I​n​v​o​i​c​e
			 */
			singular: string
		}
		maintenanceOrder: {
			/**
			 * M​a​i​n​t​e​n​a​n​c​e
			 */
			plural: string
			/**
			 * M​a​i​n​t​e​n​a​n​c​e
			 */
			singular: string
		}
		payout: {
			/**
			 * P​a​y​o​u​t​s
			 */
			plural: string
			/**
			 * P​a​y​o​u​t
			 */
			singular: string
		}
		expense: {
			/**
			 * E​x​p​e​n​s​e​s
			 */
			plural: string
			/**
			 * E​x​p​e​n​s​e
			 */
			singular: string
		}
		expenseCategory: {
			/**
			 * E​x​p​e​n​s​e​ ​C​a​t​e​g​o​r​i​e​s
			 */
			plural: string
			/**
			 * E​x​p​e​n​s​e​ ​C​a​t​e​g​o​r​y
			 */
			singular: string
		}
		file: {
			/**
			 * F​i​l​e​s
			 */
			plural: string
			/**
			 * F​i​l​e
			 */
			singular: string
		}
	}
	fields: {
		/**
		 * F​u​l​l​ ​N​a​m​e
		 */
		fullName: string
		/**
		 * L​a​b​e​l
		 */
		label: string
		/**
		 * D​a​t​e​ ​o​f​ ​B​i​r​t​h
		 */
		dob: string
		/**
		 * C​i​v​i​l​ ​I​D
		 */
		civilid: string
		/**
		 * P​h​o​n​e​ ​N​u​m​b​e​r
		 */
		phone: string
		/**
		 * E​m​a​i​l​ ​A​d​d​r​e​s​s
		 */
		email: string
		/**
		 * M​e​m​o
		 */
		memo: string
		/**
		 * A​m​o​u​n​t
		 */
		amount: string
		/**
		 * C​r​e​a​t​e​d​ ​A​t
		 */
		createdAt: string
		/**
		 * U​p​d​a​t​e​d​ ​A​t
		 */
		updatedAt: string
		/**
		 * P​o​s​t​ ​A​t
		 */
		postAt: string
		/**
		 * P​a​s​s​p​o​r​t​ ​N​u​m​b​e​r
		 */
		passportNum: string
		/**
		 * R​e​s​i​d​e​n​c​y​ ​N​u​m​b​e​r
		 */
		residencyNum: string
		/**
		 * R​e​s​i​d​e​n​c​y​ ​E​x​p​i​r​a​t​i​o​n
		 */
		residencyEnd: string
		/**
		 * N​a​t​i​o​n​a​l​i​t​y
		 */
		nationality: string
		/**
		 * B​l​o​c​k
		 */
		block: string
		/**
		 * S​t​r​e​e​t
		 */
		street: string
		/**
		 * A​v​e​n​u​e
		 */
		avenue: string
		/**
		 * N​u​m​b​e​r
		 */
		number: string
		/**
		 * P​a​c​i
		 */
		paci: string
		/**
		 * P​a​r​c​e​l
		 */
		parcel: string
		/**
		 * S​i​z​e
		 */
		size: string
		/**
		 * T​y​p​e
		 */
		type: string
		/**
		 * U​n​i​t​ ​N​u​m​b​e​r
		 */
		unitNumber: string
		/**
		 * F​l​o​o​r
		 */
		floor: string
		/**
		 * B​e​d
		 */
		bed: string
		/**
		 * B​a​t​h
		 */
		bath: string
		/**
		 * A​r​e​a
		 */
		area: string
		/**
		 * U​s​a​g​e
		 */
		usage: string
		/**
		 * M​a​r​k​e​t​ ​R​e​n​t
		 */
		marketRent: string
		/**
		 * M​o​n​t​h​l​y​ ​R​e​n​t
		 */
		monthlyRent: string
		/**
		 * D​e​p​o​s​i​t
		 */
		deposit: string
		/**
		 * S​t​a​r​t
		 */
		start: string
		/**
		 * E​n​d
		 */
		end: string
		/**
		 * S​e​n​d​ ​p​a​y​m​e​n​t​ ​r​e​m​i​n​d​e​r​s
		 */
		notify: string
		/**
		 * A​l​l​o​w​ ​t​e​n​a​n​t​ ​t​o​ ​p​a​y​ ​i​n​v​o​i​c​e​s​ ​o​n​l​i​n​e
		 */
		canPay: string
		/**
		 * T​e​n​a​n​t
		 */
		tenantId: string
		/**
		 * L​i​c​e​n​s​e
		 */
		license: string
		/**
		 * I​s​ ​P​a​i​d
		 */
		isPaid: string
		/**
		 * D​u​e​ ​A​t
		 */
		dueAt: string
		/**
		 * P​a​i​d​ ​A​t
		 */
		paidAt: string
		/**
		 * C​a​t​e​g​o​r​y
		 */
		categoryId: string
		/**
		 * T​i​t​l​e
		 */
		title: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * C​o​m​p​l​e​t​e​d​ ​A​t
		 */
		completedAt: string
		/**
		 * L​a​b​e​l​ ​(​E​n​g​l​i​s​h​)
		 */
		labelEn: string
		/**
		 * L​a​b​e​l​ ​(​A​r​a​b​i​c​)
		 */
		labelAr: string
		/**
		 * I​s​ ​G​r​o​u​p
		 */
		isGroup: string
		/**
		 * N​a​m​e
		 */
		key: string
		/**
		 * F​i​l​e​ ​N​a​m​e
		 */
		fileName: string
		/**
		 * S​i​z​e
		 */
		size2: string
	}
	buttons: {
		/**
		 * L​o​g​ ​i​n
		 */
		login: string
		/**
		 * L​o​g​ ​o​u​t
		 */
		logout: string
		/**
		 * C​o​n​t​a​c​t​ ​u​s
		 */
		contact: string
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * V​i​e​w
		 */
		view: string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * N​e​w
		 */
		'new': string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * E​x​p​o​r​t
		 */
		'export': string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * A​d​d​ ​m​u​l​t​i​p​l​e
		 */
		addMultiple: string
		/**
		 * T​o​g​g​l​e​ ​a​l​l
		 */
		toggleAll: string
		/**
		 * M​a​r​k​ ​a​s​ ​p​a​i​d
		 */
		markAsPaid: string
		/**
		 * O​p​t​i​o​n​s
		 */
		options: string
		/**
		 * R​e​n​e​w
		 */
		renew: string
		/**
		 * C​o​n​t​r​a​c​t
		 */
		contract: string
		/**
		 * P​r​i​n​t
		 */
		print: string
		/**
		 * S​e​n​d​ ​r​e​m​i​n​d​e​r
		 */
		sendReminder: string
	}
	nav: {
		/**
		 * F​i​n​a​n​c​i​a​l​s
		 */
		financials: string
		/**
		 * I​n​c​o​m​e
		 */
		income: string
		/**
		 * C​h​a​r​t​s
		 */
		charts: string
		/**
		 * D​a​t​a
		 */
		data: string
		/**
		 * O​c​c​u​p​a​n​c​y
		 */
		occupancy: string
		/**
		 * L​i​s​t
		 */
		list: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * A​c​c​o​u​n​t
		 */
		account: string
		/**
		 * I​n​f​o
		 */
		info: string
		/**
		 * N​e​t
		 */
		net: string
	}
	general: {
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * P​h​o​n​e
		 */
		phone: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * P​a​y​m​e​n​t​ ​s​c​h​e​d​u​l​e
		 */
		paymentSchedule: string
		/**
		 * B​a​l​a​n​c​e
		 */
		balance: string
		/**
		 * D​e​t​a​i​l​s
		 */
		details: string
		/**
		 * C​o​l​u​m​n​s
		 */
		columns: string
		/**
		 * A​l​l
		 */
		all: string
		/**
		 * T​o​t​a​l
		 */
		total: string
		/**
		 * f​o​r​ ​p​e​r​i​o​d
		 */
		forPeriod: string
		/**
		 * C​o​l​l​e​c​t​e​d
		 */
		collected: string
		/**
		 * U​n​c​o​l​l​e​c​t​e​d
		 */
		uncollected: string
		/**
		 * U​n​s​p​e​c​i​f​i​e​d
		 */
		unspecified: string
		/**
		 * T​h​i​s​ ​m​o​n​t​h
		 */
		thisMonth: string
		/**
		 * L​a​s​t​ ​m​o​n​t​h
		 */
		lastMonth: string
		/**
		 * T​h​e​r​e​ ​a​r​e​ ​n​o​ ​i​t​e​m​s​ ​t​o​ ​d​i​s​p​l​a​y​.
		 */
		noItems: string
	}
	charts: {
		empty: {
			/**
			 * N​o​ ​d​a​t​a
			 */
			title: string
		}
		incomePie: {
			/**
			 * I​n​c​o​m​e​:​ ​b​y​ ​p​a​y​m​e​n​t​ ​s​t​a​t​u​s
			 */
			title: string
			/**
			 * T​o​t​a​l​ ​i​n​c​o​m​e​ ​b​y​ ​p​a​y​m​e​n​t​ ​s​t​a​t​u​s​ ​f​o​r​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​p​e​r​i​o​d​.
			 */
			subtitle: string
		}
		incomeBar: {
			/**
			 * I​n​c​o​m​e​:​ ​b​y​ ​m​o​n​t​h
			 */
			title: string
			/**
			 * T​o​t​a​l​ ​i​n​c​o​m​e​ ​b​y​ ​m​o​n​t​h​ ​f​o​r​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​p​e​r​i​o​d​.
			 */
			subtitle: string
		}
		occupancyHeatmap: {
			/**
			 * O​c​c​u​p​a​n​c​y
			 */
			title: string
			/**
			 * P​e​r​c​e​n​t​a​g​e​ ​o​f​ ​o​c​c​u​p​i​e​d​ ​u​n​i​t​s​.
			 */
			subtitle: string
		}
		expensesBar: {
			/**
			 * E​x​p​e​n​s​e​s​:​ ​b​y​ ​m​o​n​t​h
			 */
			title: string
			/**
			 * T​o​t​a​l​ ​e​x​p​e​n​s​e​s​ ​b​y​ ​m​o​n​t​h​ ​f​o​r​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​p​e​r​i​o​d​.
			 */
			subtitle: string
		}
		expensesLocationTreeMap: {
			/**
			 * E​x​p​e​n​s​e​s​:​ ​b​y​ ​l​o​c​a​t​i​o​n
			 */
			title: string
			/**
			 * T​o​t​a​l​ ​e​x​p​e​n​s​e​s​ ​b​y​ ​l​o​c​a​t​i​o​n​ ​f​o​r​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​p​e​r​i​o​d​.
			 */
			subtitle: string
			/**
			 *  ​C​l​i​c​k​ ​o​n​ ​a​ ​t​i​l​e​ ​t​o​ ​z​o​o​m​ ​i​n​.​ ​T​i​l​e​ ​s​i​z​e​ ​i​s​ ​p​r​o​p​o​r​t​i​o​n​a​l​ ​t​o​ ​a​m​o​u​n​t​.
			 */
			subtitle2: string
		}
		expensesCategoryTreeMap: {
			/**
			 * E​x​p​e​n​s​e​s​:​ ​b​y​ ​c​a​t​e​g​o​r​y
			 */
			title: string
			/**
			 * T​o​t​a​l​ ​e​x​p​e​n​s​e​s​ ​b​y​ ​c​a​t​e​g​o​r​y​ ​f​o​r​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​p​e​r​i​o​d​.
			 */
			subtitle: string
			/**
			 *  ​C​l​i​c​k​ ​o​n​ ​a​ ​t​i​l​e​ ​t​o​ ​z​o​o​m​ ​i​n​.​ ​T​i​l​e​ ​s​i​z​e​ ​i​s​ ​p​r​o​p​o​r​t​i​o​n​a​l​ ​t​o​ ​a​m​o​u​n​t​.
			 */
			subtitle2: string
		}
	}
	badge: {
		/**
		 * U​p​c​o​m​i​n​g
		 */
		upcoming: string
		/**
		 * C​u​r​r​e​n​t
		 */
		current: string
		/**
		 * E​x​p​i​r​e​d
		 */
		expired: string
		/**
		 * N​o​t​ ​y​e​t​ ​d​u​e
		 */
		notYetDue: string
		/**
		 * D​u​e
		 */
		due: string
		/**
		 * P​a​s​t​ ​d​u​e
		 */
		overdue: string
		/**
		 * P​a​i​d
		 */
		paid: string
		/**
		 * I​n​ ​p​r​o​g​r​e​s​s
		 */
		inProgress: string
		/**
		 * C​o​m​p​l​e​t​e​d
		 */
		completed: string
		/**
		 * C​a​n​c​e​l​l​e​d
		 */
		cancelled: string
	}
	filter: {
		/**
		 * F​i​l​t​e​r​s
		 */
		filters: string
		/**
		 * S​t​a​r​t
		 */
		start: string
		/**
		 * E​n​d
		 */
		end: string
		/**
		 * R​a​n​g​e
		 */
		range: string
		/**
		 * M​o​n​t​h​ ​t​o​ ​d​a​t​e
		 */
		monthToDate: string
		/**
		 * L​a​s​t​ ​3​ ​m​o​n​t​h​s
		 */
		last3Months: string
		/**
		 * L​a​s​t​ ​6​ ​m​o​n​t​h​s
		 */
		last6Months: string
		/**
		 * L​a​s​t​ ​1​2​ ​m​o​n​t​h​s
		 */
		last12Months: string
		/**
		 * C​u​s​t​o​m
		 */
		custom: string
	}
	pagination: {
		/**
		 * N​e​x​t
		 */
		next: string
		/**
		 * P​r​e​v​i​o​u​s
		 */
		previous: string
		/**
		 * S​h​o​w​i​n​g
		 */
		showing: string
		/**
		 * S​h​o​w
		 */
		show: string
		/**
		 * t​o
		 */
		to: string
		/**
		 * o​f
		 */
		of: string
		/**
		 * P​a​g​e
		 */
		page: string
	}
	search: {
		/**
		 * S​e​a​r​c​h​ ​f​o​r​ ​t​e​n​a​n​t​s​,​ ​o​w​n​e​r​s​,​ ​o​r​ ​p​r​o​p​e​r​t​i​e​s​.
		 */
		title: string
		/**
		 * S​e​a​r​c​h​ ​b​y​ ​n​a​m​e​,​ ​a​d​d​r​e​s​s​,​ ​e​t​c​.
		 */
		subtitle: string
		/**
		 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d
		 */
		noResults: string
	}
	landing: {
		hero: {
			/**
			 * M​a​n​a​g​e​ ​y​o​u​r​ ​p​r​o​p​e​r​t​i​e​s
			 */
			titlePrefix: string
			/**
			 * w​i​t​h​ ​e​a​s​e​.
			 */
			titleSuffix: string
			/**
			 * P​r​o​p​e​r​t​y​ ​m​a​n​a​g​e​m​e​n​t​ ​s​i​m​p​l​i​f​i​e​d​.
			 */
			subtitle: string
			/**
			 * A​q​a​r​a​t​e​c​h​ ​p​r​o​v​i​d​e​s​ ​a​ ​c​o​m​p​r​e​h​e​n​s​i​v​e​,​ ​e​a​s​y​-​t​o​-​u​s​e​ ​p​l​a​t​f​o​r​m​ ​w​h​e​r​e​ ​y​o​u​ ​c​a​n​ ​m​a​n​a​g​e​ ​m​u​l​t​i​p​l​e​ ​p​r​o​p​e​r​t​i​e​s​,​ ​k​e​e​p​ ​t​r​a​c​k​ ​o​f​ ​i​m​p​o​r​t​a​n​t​ ​t​a​s​k​s​ ​a​n​d​ ​d​e​a​d​l​i​n​e​s​,​ ​a​n​d​ ​q​u​i​c​k​l​y​ ​a​c​c​e​s​s​ ​i​m​p​o​r​t​a​n​t​ ​i​n​f​o​r​m​a​t​i​o​n​ ​–​ ​a​l​l​ ​i​n​ ​o​n​e​ ​p​l​a​c​e​.
			 */
			description: string
		}
		features: {
			data: {
				/**
				 * D​a​t​a​ ​a​n​d​ ​A​n​a​l​y​t​i​c​s
				 */
				title: string
				bullets: {
					/**
					 * C​o​m​p​r​e​h​e​n​s​i​v​e​ ​t​r​a​c​k​i​n​g​ ​o​f​ ​p​r​o​p​e​r​t​y​-​r​e​l​a​t​e​d​ ​d​a​t​a​,​ ​i​n​c​l​u​d​i​n​g​ ​u​n​i​t​s​,​ ​l​e​a​s​e​s​,​ ​t​e​n​a​n​t​s​,​ ​a​n​d​ ​m​o​r​e​.
					 */
					track: string
					/**
					 * V​i​s​u​a​l​i​z​e​ ​y​o​u​r​ ​p​r​o​p​e​r​t​i​e​s​'​ ​f​i​n​a​n​c​i​a​l​ ​d​a​t​a​ ​t​o​ ​i​d​e​n​t​i​f​y​ ​t​r​e​n​d​s​ ​a​n​d​ ​p​a​t​t​e​r​n​s​ ​o​v​e​r​ ​t​i​m​e​.​ ​U​s​e​ ​o​u​r​ ​i​n​t​e​r​a​c​t​i​v​e​ ​d​a​s​h​b​o​a​r​d​s​ ​t​o​ ​v​i​e​w​ ​i​n​c​o​m​e​,​ ​e​x​p​e​n​s​e​s​,​ ​a​n​d​ ​p​r​o​f​i​t​/​l​o​s​s​ ​f​o​r​ ​e​a​c​h​ ​p​o​r​t​f​o​l​i​o​,​ ​p​r​o​p​e​r​t​y​,​ ​a​n​d​ ​u​n​i​t​.
					 */
					visualize: string
					/**
					 * M​o​n​i​t​o​r​ ​y​o​u​r​ ​p​r​o​p​e​r​t​i​e​s​'​ ​o​c​c​u​p​a​n​c​y​ ​r​a​t​e​s​ ​a​n​d​ ​v​a​c​a​n​c​y​ ​p​e​r​i​o​d​s​ ​u​s​i​n​g​ ​h​e​a​t​m​a​p​s​.
					 */
					monitor: string
				}
			}
			rental: {
				/**
				 * R​e​n​t​a​l​ ​P​a​y​m​e​n​t​ ​T​r​a​c​k​i​n​g
				 */
				title: string
				bullets: {
					/**
					 * E​a​s​y​ ​t​r​a​c​k​i​n​g​ ​a​n​d​ ​m​a​n​a​g​e​m​e​n​t​ ​o​f​ ​r​e​n​t​a​l​ ​p​a​y​m​e​n​t​s​ ​a​n​d​ ​l​e​a​s​e​ ​a​g​r​e​e​m​e​n​t​s​.
					 */
					track: string
					/**
					 * A​u​t​o​m​a​t​e​d​ ​p​a​y​m​e​n​t​ ​r​e​m​i​n​d​e​r​s​.
					 */
					reminders: string
				}
			}
			expense: {
				/**
				 * E​x​p​e​n​s​e​ ​T​r​a​c​k​i​n​g​ ​a​n​d​ ​V​i​s​u​a​l​i​z​a​t​i​o​n
				 */
				title: string
				bullets: {
					/**
					 * C​o​m​p​r​e​h​e​n​s​i​v​e​ ​e​x​p​e​n​s​e​ ​t​r​a​c​k​i​n​g​ ​p​r​o​v​i​d​e​s​ ​y​o​u​ ​w​i​t​h​ ​v​a​l​u​a​b​l​e​ ​g​r​a​n​u​l​a​r​i​t​y​ ​f​o​r​ ​e​x​p​e​n​s​e​ ​a​n​a​l​y​s​i​s​.​ ​C​h​o​o​s​e​ ​t​o​ ​a​t​t​r​i​b​u​t​e​ ​e​x​p​e​n​s​e​s​ ​t​o​ ​a​ ​p​o​r​t​f​o​l​i​o​,​ ​p​r​o​p​e​r​t​y​,​ ​o​r​ ​e​v​e​n​ ​a​ ​s​i​n​g​l​e​ ​u​n​i​t​.
					 */
					track: string
					/**
					 * C​a​t​e​g​o​r​i​z​e​ ​e​x​p​e​n​s​e​s​ ​u​s​i​n​g​ ​a​ ​h​i​e​r​a​r​c​h​i​c​a​l​ ​s​y​s​t​e​m​ ​t​o​ ​b​e​t​t​e​r​ ​u​n​d​e​r​s​t​a​n​d​ ​y​o​u​r​ ​e​x​p​e​n​s​e​ ​s​o​u​r​c​e​s​.
					 */
					categorize: string
					/**
					 * V​i​s​u​a​l​i​z​e​ ​e​x​p​e​n​s​e​s​ ​u​s​i​n​g​ ​i​n​t​e​r​a​c​t​i​v​e​ ​t​r​e​e​m​a​p​s​,​ ​w​h​i​c​h​ ​a​l​l​o​w​ ​y​o​u​ ​t​o​ ​q​u​i​c​k​l​y​ ​i​d​e​n​t​i​f​y​ ​y​o​u​r​ ​c​o​s​t​ ​p​a​t​t​e​r​n​s​.
					 */
					visualize: string
				}
			}
			filter: {
				/**
				 * A​d​v​a​n​c​e​d​ ​F​i​l​t​e​r​i​n​g
				 */
				title: string
				bullets: {
					/**
					 * C​u​s​t​o​m​i​z​a​b​l​e​ ​f​i​l​t​e​r​s​,​ ​s​o​ ​y​o​u​ ​c​a​n​ ​f​o​c​u​s​ ​o​n​ ​t​h​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​t​h​a​t​ ​i​s​ ​m​o​s​t​ ​r​e​l​e​v​a​n​t​ ​t​o​ ​y​o​u​.
					 */
					customizable: string
					/**
					 * F​i​l​t​e​r​ ​y​o​u​r​ ​p​r​o​p​e​r​t​i​e​s​ ​a​n​d​ ​t​e​n​a​n​t​ ​d​a​t​a​ ​b​y​ ​l​o​c​a​t​i​o​n​,​ ​i​n​c​l​u​d​i​n​g​ ​s​p​e​c​i​f​i​c​ ​p​r​o​p​e​r​t​i​e​s​ ​o​r​ ​u​n​i​t​s​ ​w​i​t​h​i​n​ ​p​r​o​p​e​r​t​i​e​s​.
					 */
					properties: string
					/**
					 * F​i​l​t​e​r​ ​b​y​ ​t​i​m​e​,​ ​i​n​c​l​u​d​i​n​g​ ​s​p​e​c​i​f​i​c​ ​d​a​t​e​ ​r​a​n​g​e​s​ ​o​r​ ​t​i​m​e​ ​p​e​r​i​o​d​s​.
					 */
					time: string
				}
			}
			document: {
				/**
				 * D​o​c​u​m​e​n​t​ ​M​a​n​a​g​e​m​e​n​t
				 */
				title: string
				bullets: {
					/**
					 * S​t​o​r​e​ ​a​n​d​ ​m​a​n​a​g​e​ ​i​m​p​o​r​t​a​n​t​ ​d​o​c​u​m​e​n​t​s​ ​r​e​l​a​t​e​d​ ​t​o​ ​y​o​u​r​ ​p​r​o​p​e​r​t​i​e​s​ ​a​n​d​ ​t​e​n​a​n​t​s​,​ ​i​n​c​l​u​d​i​n​g​ ​l​e​a​s​e​ ​a​g​r​e​e​m​e​n​t​s​,​ ​r​e​n​t​a​l​ ​p​a​y​m​e​n​t​ ​r​e​c​e​i​p​t​s​,​ ​a​n​d​ ​m​a​i​n​t​e​n​a​n​c​e​ ​r​e​c​o​r​d​s​.
					 */
					upload: string
					/**
					 * A​c​c​e​s​s​ ​y​o​u​r​ ​d​o​c​u​m​e​n​t​s​ ​f​r​o​m​ ​a​n​y​w​h​e​r​e​,​ ​u​s​i​n​g​ ​a​n​y​ ​d​e​v​i​c​e​.
					 */
					access: string
				}
			}
			search: {
				/**
				 * P​o​w​e​r​f​u​l​ ​S​e​a​r​c​h
				 */
				title: string
				bullets: {
					/**
					 * S​e​a​r​c​h​ ​t​h​r​o​u​g​h​ ​a​l​l​ ​o​f​ ​y​o​u​r​ ​d​a​t​a​ ​a​t​ ​t​h​e​ ​s​a​m​e​ ​t​i​m​e​.
					 */
					all: string
					/**
					 * F​i​n​d​ ​w​h​a​t​ ​y​o​u​'​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​w​i​t​h​o​u​t​ ​k​n​o​w​i​n​g​ ​t​h​e​ ​e​x​a​c​t​ ​s​p​e​l​l​i​n​g​.
					 */
					spell: string
				}
			}
		}
		secondaryFeatures: {
			managers: {
				/**
				 * F​o​r​ ​p​r​o​p​e​r​t​y​ ​m​a​n​a​g​e​r​s
				 */
				summary: string
				/**
				 * S​t​r​e​a​m​l​i​n​e​ ​y​o​u​r​ ​w​o​r​k​f​l​o​w​s
				 */
				name: string
				/**
				 * L​e​v​e​r​a​g​e​ ​o​u​r​ ​p​o​w​e​r​f​u​l​ ​t​o​o​l​s​ ​t​o​ ​k​e​e​p​ ​t​r​a​c​k​ ​o​f​ ​a​l​l​ ​y​o​u​r​ ​p​r​o​p​e​r​t​i​e​s​.​ ​A​q​a​r​a​t​e​c​h​ ​h​e​l​p​s​ ​y​o​u​ ​o​r​g​a​n​i​z​e​ ​y​o​u​r​ ​b​u​s​i​n​e​s​s​ ​a​n​d​ ​w​o​r​k​ ​m​o​r​e​ ​e​f​f​i​c​i​e​n​t​l​y​.
				 */
				description: string
			}
			owners: {
				/**
				 * F​o​r​ ​o​w​n​e​r​s
				 */
				summary: string
				/**
				 * C​o​m​p​l​e​t​e​ ​v​i​s​i​b​i​l​i​t​y
				 */
				name: string
				/**
				 * U​s​e​ ​o​u​r​ ​d​a​s​h​b​o​a​r​d​ ​t​o​ ​a​c​c​e​s​s​ ​a​n​d​ ​m​o​n​i​t​o​r​ ​a​l​l​ ​o​f​ ​y​o​u​r​ ​p​r​o​p​e​r​t​y​ ​i​n​f​o​r​m​a​t​i​o​n​,​ ​g​r​a​n​t​i​n​g​ ​y​o​u​ ​p​e​a​c​e​ ​o​f​ ​m​i​n​d​ ​h​e​l​p​i​n​g​ ​y​o​u​ ​m​a​k​e​ ​i​n​f​o​r​m​e​d​ ​d​e​c​i​s​i​o​n​s​.
				 */
				description: string
			}
			tenants: {
				/**
				 * F​o​r​ ​t​e​n​a​n​t​s
				 */
				summary: string
				/**
				 * H​a​s​s​l​e​-​f​r​e​e​ ​r​e​n​t​a​l​s
				 */
				name: string
				/**
				 * A​q​a​r​a​t​e​c​h​ ​s​i​m​p​l​i​f​i​e​s​ ​t​h​e​ ​r​e​n​t​a​l​ ​p​r​o​c​e​s​s​ ​b​y​ ​a​l​l​o​w​i​n​g​ ​t​e​n​a​n​t​s​ ​t​o​ ​t​r​a​c​k​ ​t​h​e​i​r​ ​p​a​y​m​e​n​t​s​ ​a​n​d​ ​l​e​a​s​e​s​.
				 */
				description: string
			}
		}
		callToAction: {
			/**
			 * G​e​t​ ​s​t​a​r​t​e​d​ ​t​o​d​a​y
			 */
			title: string
			/**
			 * T​r​y​ ​A​q​a​r​a​t​e​c​h​ ​a​n​d​ ​e​x​p​e​r​i​e​n​c​e​ ​t​h​e​ ​e​a​s​e​ ​a​n​d​ ​c​o​n​v​e​n​i​e​n​c​e​ ​o​f​ ​m​a​n​a​g​i​n​g​ ​y​o​u​r​ ​p​r​o​p​e​r​t​i​e​s​ ​w​i​t​h​ ​j​u​s​t​ ​a​ ​f​e​w​ ​c​l​i​c​k​s​!​ ​S​i​g​n​ ​u​p​ ​n​o​w​ ​a​n​d​ ​s​e​e​ ​t​h​e​ ​d​i​f​f​e​r​e​n​c​e​ ​i​t​ ​c​a​n​ ​m​a​k​e​ ​f​o​r​ ​y​o​u​r​ ​b​u​s​i​n​e​s​s​.
			 */
			description: string
			/**
			 * C​r​e​a​t​e​ ​A​c​c​o​u​n​t
			 */
			button: string
		}
		footer: {
			/**
			 * A​q​a​r​a​t​e​c​h​,​ ​L​L​C​.​ ​A​l​l​ ​r​i​g​h​t​s​ ​r​e​s​e​r​v​e​d​.
			 */
			legal: string
		}
		/**
		 * L​o​c​a​t​i​o​n
		 */
		location: string
		/**
		 * O​n​l​i​n​e
		 */
		online: string
		/**
		 * M​a​p
		 */
		map: string
	}
	aqaratech: {
		/**
		 * A​q​a​r​a​t​e​c​h​,​ ​L​L​C​.
		 */
		fullName: string
		/**
		 * A​q​a​r​a​t​e​c​h
		 */
		shortName: string
		address: {
			/**
			 * 2​5​ ​A​l​s​h​u​h​a​d​a​ ​S​t​,​ ​S​u​l​a​i​m​a​n​ ​T​o​w​e​r
			 */
			line1: string
			/**
			 * S​h​a​r​q​,​ ​1​5​3​0​5​,​ ​K​u​w​a​i​t
			 */
			line2: string
		}
	}
	other: {
		/**
		 * P​r​o​g​r​e​s​s
		 */
		progress: string
		/**
		 * V​a​c​a​n​c​y
		 */
		vacancy: string
		/**
		 * V​a​c​a​n​t
		 */
		vacant: string
		/**
		 * O​c​c​u​p​i​e​d
		 */
		occupied: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​?
		 */
		areYouSure: string
	}
}

export type TranslationFunctions = {
	entity: {
		user: {
			/**
			 * Users
			 */
			plural: () => LocalizedString
			/**
			 * User
			 */
			singular: () => LocalizedString
		}
		organization: {
			/**
			 * Organizations
			 */
			plural: () => LocalizedString
			/**
			 * Organization
			 */
			singular: () => LocalizedString
		}
		role: {
			/**
			 * Roles
			 */
			plural: () => LocalizedString
			/**
			 * Role
			 */
			singular: () => LocalizedString
		}
		tenant: {
			/**
			 * Tenants
			 */
			plural: () => LocalizedString
			/**
			 * Tenant
			 */
			singular: () => LocalizedString
		}
		portfolio: {
			/**
			 * Owners
			 */
			plural: () => LocalizedString
			/**
			 * Owner
			 */
			singular: () => LocalizedString
		}
		property: {
			/**
			 * Properties
			 */
			plural: () => LocalizedString
			/**
			 * Property
			 */
			singular: () => LocalizedString
		}
		unit: {
			/**
			 * Units
			 */
			plural: () => LocalizedString
			/**
			 * Unit
			 */
			singular: () => LocalizedString
		}
		lease: {
			/**
			 * Leases
			 */
			plural: () => LocalizedString
			/**
			 * Lease
			 */
			singular: () => LocalizedString
		}
		leaseInvoice: {
			/**
			 * Invoices
			 */
			plural: () => LocalizedString
			/**
			 * Invoice
			 */
			singular: () => LocalizedString
		}
		maintenanceOrder: {
			/**
			 * Maintenance
			 */
			plural: () => LocalizedString
			/**
			 * Maintenance
			 */
			singular: () => LocalizedString
		}
		payout: {
			/**
			 * Payouts
			 */
			plural: () => LocalizedString
			/**
			 * Payout
			 */
			singular: () => LocalizedString
		}
		expense: {
			/**
			 * Expenses
			 */
			plural: () => LocalizedString
			/**
			 * Expense
			 */
			singular: () => LocalizedString
		}
		expenseCategory: {
			/**
			 * Expense Categories
			 */
			plural: () => LocalizedString
			/**
			 * Expense Category
			 */
			singular: () => LocalizedString
		}
		file: {
			/**
			 * Files
			 */
			plural: () => LocalizedString
			/**
			 * File
			 */
			singular: () => LocalizedString
		}
	}
	fields: {
		/**
		 * Full Name
		 */
		fullName: () => LocalizedString
		/**
		 * Label
		 */
		label: () => LocalizedString
		/**
		 * Date of Birth
		 */
		dob: () => LocalizedString
		/**
		 * Civil ID
		 */
		civilid: () => LocalizedString
		/**
		 * Phone Number
		 */
		phone: () => LocalizedString
		/**
		 * Email Address
		 */
		email: () => LocalizedString
		/**
		 * Memo
		 */
		memo: () => LocalizedString
		/**
		 * Amount
		 */
		amount: () => LocalizedString
		/**
		 * Created At
		 */
		createdAt: () => LocalizedString
		/**
		 * Updated At
		 */
		updatedAt: () => LocalizedString
		/**
		 * Post At
		 */
		postAt: () => LocalizedString
		/**
		 * Passport Number
		 */
		passportNum: () => LocalizedString
		/**
		 * Residency Number
		 */
		residencyNum: () => LocalizedString
		/**
		 * Residency Expiration
		 */
		residencyEnd: () => LocalizedString
		/**
		 * Nationality
		 */
		nationality: () => LocalizedString
		/**
		 * Block
		 */
		block: () => LocalizedString
		/**
		 * Street
		 */
		street: () => LocalizedString
		/**
		 * Avenue
		 */
		avenue: () => LocalizedString
		/**
		 * Number
		 */
		number: () => LocalizedString
		/**
		 * Paci
		 */
		paci: () => LocalizedString
		/**
		 * Parcel
		 */
		parcel: () => LocalizedString
		/**
		 * Size
		 */
		size: () => LocalizedString
		/**
		 * Type
		 */
		type: () => LocalizedString
		/**
		 * Unit Number
		 */
		unitNumber: () => LocalizedString
		/**
		 * Floor
		 */
		floor: () => LocalizedString
		/**
		 * Bed
		 */
		bed: () => LocalizedString
		/**
		 * Bath
		 */
		bath: () => LocalizedString
		/**
		 * Area
		 */
		area: () => LocalizedString
		/**
		 * Usage
		 */
		usage: () => LocalizedString
		/**
		 * Market Rent
		 */
		marketRent: () => LocalizedString
		/**
		 * Monthly Rent
		 */
		monthlyRent: () => LocalizedString
		/**
		 * Deposit
		 */
		deposit: () => LocalizedString
		/**
		 * Start
		 */
		start: () => LocalizedString
		/**
		 * End
		 */
		end: () => LocalizedString
		/**
		 * Send payment reminders
		 */
		notify: () => LocalizedString
		/**
		 * Allow tenant to pay invoices online
		 */
		canPay: () => LocalizedString
		/**
		 * Tenant
		 */
		tenantId: () => LocalizedString
		/**
		 * License
		 */
		license: () => LocalizedString
		/**
		 * Is Paid
		 */
		isPaid: () => LocalizedString
		/**
		 * Due At
		 */
		dueAt: () => LocalizedString
		/**
		 * Paid At
		 */
		paidAt: () => LocalizedString
		/**
		 * Category
		 */
		categoryId: () => LocalizedString
		/**
		 * Title
		 */
		title: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Completed At
		 */
		completedAt: () => LocalizedString
		/**
		 * Label (English)
		 */
		labelEn: () => LocalizedString
		/**
		 * Label (Arabic)
		 */
		labelAr: () => LocalizedString
		/**
		 * Is Group
		 */
		isGroup: () => LocalizedString
		/**
		 * Name
		 */
		key: () => LocalizedString
		/**
		 * File Name
		 */
		fileName: () => LocalizedString
		/**
		 * Size
		 */
		size2: () => LocalizedString
	}
	buttons: {
		/**
		 * Log in
		 */
		login: () => LocalizedString
		/**
		 * Log out
		 */
		logout: () => LocalizedString
		/**
		 * Contact us
		 */
		contact: () => LocalizedString
		/**
		 * Search
		 */
		search: () => LocalizedString
		/**
		 * View
		 */
		view: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * New
		 */
		'new': () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Export
		 */
		'export': () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Add multiple
		 */
		addMultiple: () => LocalizedString
		/**
		 * Toggle all
		 */
		toggleAll: () => LocalizedString
		/**
		 * Mark as paid
		 */
		markAsPaid: () => LocalizedString
		/**
		 * Options
		 */
		options: () => LocalizedString
		/**
		 * Renew
		 */
		renew: () => LocalizedString
		/**
		 * Contract
		 */
		contract: () => LocalizedString
		/**
		 * Print
		 */
		print: () => LocalizedString
		/**
		 * Send reminder
		 */
		sendReminder: () => LocalizedString
	}
	nav: {
		/**
		 * Financials
		 */
		financials: () => LocalizedString
		/**
		 * Income
		 */
		income: () => LocalizedString
		/**
		 * Charts
		 */
		charts: () => LocalizedString
		/**
		 * Data
		 */
		data: () => LocalizedString
		/**
		 * Occupancy
		 */
		occupancy: () => LocalizedString
		/**
		 * List
		 */
		list: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Account
		 */
		account: () => LocalizedString
		/**
		 * Info
		 */
		info: () => LocalizedString
		/**
		 * Net
		 */
		net: () => LocalizedString
	}
	general: {
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Phone
		 */
		phone: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Payment schedule
		 */
		paymentSchedule: () => LocalizedString
		/**
		 * Balance
		 */
		balance: () => LocalizedString
		/**
		 * Details
		 */
		details: () => LocalizedString
		/**
		 * Columns
		 */
		columns: () => LocalizedString
		/**
		 * All
		 */
		all: () => LocalizedString
		/**
		 * Total
		 */
		total: () => LocalizedString
		/**
		 * for period
		 */
		forPeriod: () => LocalizedString
		/**
		 * Collected
		 */
		collected: () => LocalizedString
		/**
		 * Uncollected
		 */
		uncollected: () => LocalizedString
		/**
		 * Unspecified
		 */
		unspecified: () => LocalizedString
		/**
		 * This month
		 */
		thisMonth: () => LocalizedString
		/**
		 * Last month
		 */
		lastMonth: () => LocalizedString
		/**
		 * There are no items to display.
		 */
		noItems: () => LocalizedString
	}
	charts: {
		empty: {
			/**
			 * No data
			 */
			title: () => LocalizedString
		}
		incomePie: {
			/**
			 * Income: by payment status
			 */
			title: () => LocalizedString
			/**
			 * Total income by payment status for the selected period.
			 */
			subtitle: () => LocalizedString
		}
		incomeBar: {
			/**
			 * Income: by month
			 */
			title: () => LocalizedString
			/**
			 * Total income by month for the selected period.
			 */
			subtitle: () => LocalizedString
		}
		occupancyHeatmap: {
			/**
			 * Occupancy
			 */
			title: () => LocalizedString
			/**
			 * Percentage of occupied units.
			 */
			subtitle: () => LocalizedString
		}
		expensesBar: {
			/**
			 * Expenses: by month
			 */
			title: () => LocalizedString
			/**
			 * Total expenses by month for the selected period.
			 */
			subtitle: () => LocalizedString
		}
		expensesLocationTreeMap: {
			/**
			 * Expenses: by location
			 */
			title: () => LocalizedString
			/**
			 * Total expenses by location for the selected period.
			 */
			subtitle: () => LocalizedString
			/**
			 *  Click on a tile to zoom in. Tile size is proportional to amount.
			 */
			subtitle2: () => LocalizedString
		}
		expensesCategoryTreeMap: {
			/**
			 * Expenses: by category
			 */
			title: () => LocalizedString
			/**
			 * Total expenses by category for the selected period.
			 */
			subtitle: () => LocalizedString
			/**
			 *  Click on a tile to zoom in. Tile size is proportional to amount.
			 */
			subtitle2: () => LocalizedString
		}
	}
	badge: {
		/**
		 * Upcoming
		 */
		upcoming: () => LocalizedString
		/**
		 * Current
		 */
		current: () => LocalizedString
		/**
		 * Expired
		 */
		expired: () => LocalizedString
		/**
		 * Not yet due
		 */
		notYetDue: () => LocalizedString
		/**
		 * Due
		 */
		due: () => LocalizedString
		/**
		 * Past due
		 */
		overdue: () => LocalizedString
		/**
		 * Paid
		 */
		paid: () => LocalizedString
		/**
		 * In progress
		 */
		inProgress: () => LocalizedString
		/**
		 * Completed
		 */
		completed: () => LocalizedString
		/**
		 * Cancelled
		 */
		cancelled: () => LocalizedString
	}
	filter: {
		/**
		 * Filters
		 */
		filters: () => LocalizedString
		/**
		 * Start
		 */
		start: () => LocalizedString
		/**
		 * End
		 */
		end: () => LocalizedString
		/**
		 * Range
		 */
		range: () => LocalizedString
		/**
		 * Month to date
		 */
		monthToDate: () => LocalizedString
		/**
		 * Last 3 months
		 */
		last3Months: () => LocalizedString
		/**
		 * Last 6 months
		 */
		last6Months: () => LocalizedString
		/**
		 * Last 12 months
		 */
		last12Months: () => LocalizedString
		/**
		 * Custom
		 */
		custom: () => LocalizedString
	}
	pagination: {
		/**
		 * Next
		 */
		next: () => LocalizedString
		/**
		 * Previous
		 */
		previous: () => LocalizedString
		/**
		 * Showing
		 */
		showing: () => LocalizedString
		/**
		 * Show
		 */
		show: () => LocalizedString
		/**
		 * to
		 */
		to: () => LocalizedString
		/**
		 * of
		 */
		of: () => LocalizedString
		/**
		 * Page
		 */
		page: () => LocalizedString
	}
	search: {
		/**
		 * Search for tenants, owners, or properties.
		 */
		title: () => LocalizedString
		/**
		 * Search by name, address, etc.
		 */
		subtitle: () => LocalizedString
		/**
		 * No results found
		 */
		noResults: () => LocalizedString
	}
	landing: {
		hero: {
			/**
			 * Manage your properties
			 */
			titlePrefix: () => LocalizedString
			/**
			 * with ease.
			 */
			titleSuffix: () => LocalizedString
			/**
			 * Property management simplified.
			 */
			subtitle: () => LocalizedString
			/**
			 * Aqaratech provides a comprehensive, easy-to-use platform where you can manage multiple properties, keep track of important tasks and deadlines, and quickly access important information – all in one place.
			 */
			description: () => LocalizedString
		}
		features: {
			data: {
				/**
				 * Data and Analytics
				 */
				title: () => LocalizedString
				bullets: {
					/**
					 * Comprehensive tracking of property-related data, including units, leases, tenants, and more.
					 */
					track: () => LocalizedString
					/**
					 * Visualize your properties' financial data to identify trends and patterns over time. Use our interactive dashboards to view income, expenses, and profit/loss for each portfolio, property, and unit.
					 */
					visualize: () => LocalizedString
					/**
					 * Monitor your properties' occupancy rates and vacancy periods using heatmaps.
					 */
					monitor: () => LocalizedString
				}
			}
			rental: {
				/**
				 * Rental Payment Tracking
				 */
				title: () => LocalizedString
				bullets: {
					/**
					 * Easy tracking and management of rental payments and lease agreements.
					 */
					track: () => LocalizedString
					/**
					 * Automated payment reminders.
					 */
					reminders: () => LocalizedString
				}
			}
			expense: {
				/**
				 * Expense Tracking and Visualization
				 */
				title: () => LocalizedString
				bullets: {
					/**
					 * Comprehensive expense tracking provides you with valuable granularity for expense analysis. Choose to attribute expenses to a portfolio, property, or even a single unit.
					 */
					track: () => LocalizedString
					/**
					 * Categorize expenses using a hierarchical system to better understand your expense sources.
					 */
					categorize: () => LocalizedString
					/**
					 * Visualize expenses using interactive treemaps, which allow you to quickly identify your cost patterns.
					 */
					visualize: () => LocalizedString
				}
			}
			filter: {
				/**
				 * Advanced Filtering
				 */
				title: () => LocalizedString
				bullets: {
					/**
					 * Customizable filters, so you can focus on the information that is most relevant to you.
					 */
					customizable: () => LocalizedString
					/**
					 * Filter your properties and tenant data by location, including specific properties or units within properties.
					 */
					properties: () => LocalizedString
					/**
					 * Filter by time, including specific date ranges or time periods.
					 */
					time: () => LocalizedString
				}
			}
			document: {
				/**
				 * Document Management
				 */
				title: () => LocalizedString
				bullets: {
					/**
					 * Store and manage important documents related to your properties and tenants, including lease agreements, rental payment receipts, and maintenance records.
					 */
					upload: () => LocalizedString
					/**
					 * Access your documents from anywhere, using any device.
					 */
					access: () => LocalizedString
				}
			}
			search: {
				/**
				 * Powerful Search
				 */
				title: () => LocalizedString
				bullets: {
					/**
					 * Search through all of your data at the same time.
					 */
					all: () => LocalizedString
					/**
					 * Find what you're looking for without knowing the exact spelling.
					 */
					spell: () => LocalizedString
				}
			}
		}
		secondaryFeatures: {
			managers: {
				/**
				 * For property managers
				 */
				summary: () => LocalizedString
				/**
				 * Streamline your workflows
				 */
				name: () => LocalizedString
				/**
				 * Leverage our powerful tools to keep track of all your properties. Aqaratech helps you organize your business and work more efficiently.
				 */
				description: () => LocalizedString
			}
			owners: {
				/**
				 * For owners
				 */
				summary: () => LocalizedString
				/**
				 * Complete visibility
				 */
				name: () => LocalizedString
				/**
				 * Use our dashboard to access and monitor all of your property information, granting you peace of mind helping you make informed decisions.
				 */
				description: () => LocalizedString
			}
			tenants: {
				/**
				 * For tenants
				 */
				summary: () => LocalizedString
				/**
				 * Hassle-free rentals
				 */
				name: () => LocalizedString
				/**
				 * Aqaratech simplifies the rental process by allowing tenants to track their payments and leases.
				 */
				description: () => LocalizedString
			}
		}
		callToAction: {
			/**
			 * Get started today
			 */
			title: () => LocalizedString
			/**
			 * Try Aqaratech and experience the ease and convenience of managing your properties with just a few clicks! Sign up now and see the difference it can make for your business.
			 */
			description: () => LocalizedString
			/**
			 * Create Account
			 */
			button: () => LocalizedString
		}
		footer: {
			/**
			 * Aqaratech, LLC. All rights reserved.
			 */
			legal: () => LocalizedString
		}
		/**
		 * Location
		 */
		location: () => LocalizedString
		/**
		 * Online
		 */
		online: () => LocalizedString
		/**
		 * Map
		 */
		map: () => LocalizedString
	}
	aqaratech: {
		/**
		 * Aqaratech, LLC.
		 */
		fullName: () => LocalizedString
		/**
		 * Aqaratech
		 */
		shortName: () => LocalizedString
		address: {
			/**
			 * 25 Alshuhada St, Sulaiman Tower
			 */
			line1: () => LocalizedString
			/**
			 * Sharq, 15305, Kuwait
			 */
			line2: () => LocalizedString
		}
	}
	other: {
		/**
		 * Progress
		 */
		progress: () => LocalizedString
		/**
		 * Vacancy
		 */
		vacancy: () => LocalizedString
		/**
		 * Vacant
		 */
		vacant: () => LocalizedString
		/**
		 * Occupied
		 */
		occupied: () => LocalizedString
		/**
		 * Are you sure?
		 */
		areYouSure: () => LocalizedString
	}
}

export type Formatters = {}
