// prettier-ignore
export const countries = [
    {"alpha3Code":"AFG","alpha2Code":"AF","phone":93,"name":"Afghanistan","nameAr":"أفغانستان"},
    {"alpha3Code":"ALA","alpha2Code":"AX","phone":358,"name":"Aland Islands","nameAr":"جزر آلاند"},
    {"alpha3Code":"ALB","alpha2Code":"AL","phone":355,"name":"Albania","nameAr":"ألبانيا"},
    {"alpha3Code":"DZA","alpha2Code":"DZ","phone":213,"name":"Algeria","nameAr":"الجزائر"},
    {"alpha3Code":"ASM","alpha2Code":"AS","phone":1684,"name":"American Samoa","nameAr":"ساموا الأمريكية"},
    {"alpha3Code":"AND","alpha2Code":"AD","phone":376,"name":"Andorra","nameAr":"أندورا"},
    {"alpha3Code":"AGO","alpha2Code":"AO","phone":244,"name":"Angola","nameAr":"أنغولا"},
    {"alpha3Code":"AIA","alpha2Code":"AI","phone":1264,"name":"Anguilla","nameAr":"أنغيلا"},
    {"alpha3Code":"ATA","alpha2Code":"AQ","phone":672,"name":"Antarctica","nameAr":"أنتاركتيكا"},
    {"alpha3Code":"ATG","alpha2Code":"AG","phone":1268,"name":"Antigua and Barbuda","nameAr":"أنتيغوا وبربودا"},
    {"alpha3Code":"ARG","alpha2Code":"AR","phone":54,"name":"Argentina","nameAr":"الأرجنتين"},
    {"alpha3Code":"ARM","alpha2Code":"AM","phone":374,"name":"Armenia","nameAr":"أرمينيا"},
    {"alpha3Code":"ABW","alpha2Code":"AW","phone":297,"name":"Aruba","nameAr":"أروبا"},
    {"alpha3Code":"AUS","alpha2Code":"AU","phone":61,"name":"Australia","nameAr":"أستراليا"},
    {"alpha3Code":"AUT","alpha2Code":"AT","phone":43,"name":"Austria","nameAr":"النمسا"},
    {"alpha3Code":"AZE","alpha2Code":"AZ","phone":994,"name":"Azerbaijan","nameAr":"أذربيجان"},
    {"alpha3Code":"BHS","alpha2Code":"BS","phone":1242,"name":"Bahamas","nameAr":"جزر البهاما"},
    {"alpha3Code":"BHR","alpha2Code":"BH","phone":973,"name":"Bahrain","nameAr":"البحرين"},
    {"alpha3Code":"BGD","alpha2Code":"BD","phone":880,"name":"Bangladesh","nameAr":"بنغلاديش"},
    {"alpha3Code":"BRB","alpha2Code":"BB","phone":1246,"name":"Barbados","nameAr":"بربادوس"},
    {"alpha3Code":"BLR","alpha2Code":"BY","phone":375,"name":"Belarus","nameAr":"بيلاروسيا"},
    {"alpha3Code":"BEL","alpha2Code":"BE","phone":32,"name":"Belgium","nameAr":"بلجيكا"},
    {"alpha3Code":"BLZ","alpha2Code":"BZ","phone":501,"name":"Belize","nameAr":"بليز"},
    {"alpha3Code":"BEN","alpha2Code":"BJ","phone":229,"name":"Benin","nameAr":"بنين"},
    {"alpha3Code":"BMU","alpha2Code":"BM","phone":1441,"name":"Bermuda","nameAr":"برمودا"},
    {"alpha3Code":"BTN","alpha2Code":"BT","phone":975,"name":"Bhutan","nameAr":"بوتان"},
    {"alpha3Code":"BOL","alpha2Code":"BO","phone":591,"name":"Bolivia","nameAr":"بوليفيا"},
    {"alpha3Code":"BES","alpha2Code":"BQ","phone":599,"name":"Bonaire, Sint Eustatius and Saba","nameAr":"بونير وسانت يوستاتيوس وسابا"},
    {"alpha3Code":"BIH","alpha2Code":"BA","phone":387,"name":"Bosnia and Herzegovina","nameAr":"البوسنة والهرسك"},
    {"alpha3Code":"BWA","alpha2Code":"BW","phone":267,"name":"Botswana","nameAr":"بوتسوانا"},
    {"alpha3Code":"BVT","alpha2Code":"BV","phone":55,"name":"Bouvet Island","nameAr":"جزيرة بوفيت"},
    {"alpha3Code":"BRA","alpha2Code":"BR","phone":55,"name":"Brazil","nameAr":"البرازيل"},
    {"alpha3Code":"IOT","alpha2Code":"IO","phone":246,"name":"British Indian Ocean Territory","nameAr":"إقليم المحيط البريطاني الهندي"},
    {"alpha3Code":"BRN","alpha2Code":"BN","phone":673,"name":"Brunei Darussalam","nameAr":"بروناي دار السلام"},
    {"alpha3Code":"BGR","alpha2Code":"BG","phone":359,"name":"Bulgaria","nameAr":"بلغاريا"},
    {"alpha3Code":"BFA","alpha2Code":"BF","phone":226,"name":"Burkina Faso","nameAr":"بوركينا فاسو"},
    {"alpha3Code":"BDI","alpha2Code":"BI","phone":257,"name":"Burundi","nameAr":"بوروندي"},
    {"alpha3Code":"KHM","alpha2Code":"KH","phone":855,"name":"Cambodia","nameAr":"كمبوديا"},
    {"alpha3Code":"CMR","alpha2Code":"CM","phone":237,"name":"Cameroon","nameAr":"الكاميرون"},
    {"alpha3Code":"CAN","alpha2Code":"CA","phone":1,"name":"Canada","nameAr":"كندا"},
    {"alpha3Code":"CPV","alpha2Code":"CV","phone":238,"name":"Cape Verde","nameAr":"الرأس الأخضر"},
    {"alpha3Code":"CYM","alpha2Code":"KY","phone":1345,"name":"Cayman Islands","nameAr":"جزر كايمان"},
    {"alpha3Code":"CAF","alpha2Code":"CF","phone":236,"name":"Central African Republic","nameAr":"جمهورية افريقيا الوسطى"},
    {"alpha3Code":"TCD","alpha2Code":"TD","phone":235,"name":"Chad","nameAr":"تشاد"},
    {"alpha3Code":"CHL","alpha2Code":"CL","phone":56,"name":"Chile","nameAr":"تشيلي"},
    {"alpha3Code":"CHN","alpha2Code":"CN","phone":86,"name":"China","nameAr":"الصين"},
    {"alpha3Code":"CXR","alpha2Code":"CX","phone":61,"name":"Christmas Island","nameAr":"جزيرة الكريسماس"},
    {"alpha3Code":"CCK","alpha2Code":"CC","phone":672,"name":"Cocos (Keeling) Islands","nameAr":"جزر كوكوس (كيلينغ)"},
    {"alpha3Code":"COL","alpha2Code":"CO","phone":57,"name":"Colombia","nameAr":"كولومبيا"},
    {"alpha3Code":"COM","alpha2Code":"KM","phone":269,"name":"Comoros","nameAr":"جزر القمر"},
    {"alpha3Code":"COG","alpha2Code":"CG","phone":242,"name":"Congo","nameAr":"الكونغو"},
    {"alpha3Code":"COD","alpha2Code":"CD","phone":242,"name":"Congo, Democratic Republic of the Congo","nameAr":"الكونغو ، جمهورية الكونغو الديمقراطية"},
    {"alpha3Code":"COK","alpha2Code":"CK","phone":682,"name":"Cook Islands","nameAr":"جزر كوك"},
    {"alpha3Code":"CRI","alpha2Code":"CR","phone":506,"name":"Costa Rica","nameAr":"كوستا ريكا"},
    {"alpha3Code":"CIV","alpha2Code":"CI","phone":225,"name":"Cote D'Ivoire","nameAr":"ساحل العاج"},
    {"alpha3Code":"HRV","alpha2Code":"HR","phone":385,"name":"Croatia","nameAr":"كرواتيا"},
    {"alpha3Code":"CUB","alpha2Code":"CU","phone":53,"name":"Cuba","nameAr":"كوبا"},
    {"alpha3Code":"CUW","alpha2Code":"CW","phone":599,"name":"Curacao","nameAr":"كوراكاو"},
    {"alpha3Code":"CYP","alpha2Code":"CY","phone":357,"name":"Cyprus","nameAr":"قبرص"},
    {"alpha3Code":"CZE","alpha2Code":"CZ","phone":420,"name":"Czech Republic","nameAr":"الجمهورية التشيكية"},
    {"alpha3Code":"DNK","alpha2Code":"DK","phone":45,"name":"Denmark","nameAr":"الدنمارك"},
    {"alpha3Code":"DJI","alpha2Code":"DJ","phone":253,"name":"Djibouti","nameAr":"جيبوتي"},
    {"alpha3Code":"DMA","alpha2Code":"DM","phone":1767,"name":"Dominica","nameAr":"دومينيكا"},
    {"alpha3Code":"DOM","alpha2Code":"DO","phone":1809,"name":"Dominican Republic","nameAr":"جمهورية الدومنيكان"},
    {"alpha3Code":"ECU","alpha2Code":"EC","phone":593,"name":"Ecuador","nameAr":"الاكوادور"},
    {"alpha3Code":"EGY","alpha2Code":"EG","phone":20,"name":"Egypt","nameAr":"مصر"},
    {"alpha3Code":"SLV","alpha2Code":"SV","phone":503,"name":"El Salvador","nameAr":"السلفادور"},
    {"alpha3Code":"GNQ","alpha2Code":"GQ","phone":240,"name":"Equatorial Guinea","nameAr":"غينيا الإستوائية"},
    {"alpha3Code":"ERI","alpha2Code":"ER","phone":291,"name":"Eritrea","nameAr":"إريتريا"},
    {"alpha3Code":"EST","alpha2Code":"EE","phone":372,"name":"Estonia","nameAr":"إستونيا"},
    {"alpha3Code":"ETH","alpha2Code":"ET","phone":251,"name":"Ethiopia","nameAr":"أثيوبيا"},
    {"alpha3Code":"FLK","alpha2Code":"FK","phone":500,"name":"Falkland Islands (Malvinas)","nameAr":"جزر فوكلاند (مالفيناس)"},
    {"alpha3Code":"FRO","alpha2Code":"FO","phone":298,"name":"Faroe Islands","nameAr":"جزر فاروس"},
    {"alpha3Code":"FJI","alpha2Code":"FJ","phone":679,"name":"Fiji","nameAr":"فيجي"},
    {"alpha3Code":"FIN","alpha2Code":"FI","phone":358,"name":"Finland","nameAr":"فنلندا"},
    {"alpha3Code":"FRA","alpha2Code":"FR","phone":33,"name":"France","nameAr":"فرنسا"},
    {"alpha3Code":"GUF","alpha2Code":"GF","phone":594,"name":"French Guiana","nameAr":"غيانا الفرنسية"},
    {"alpha3Code":"PYF","alpha2Code":"PF","phone":689,"name":"French Polynesia","nameAr":"بولينيزيا الفرنسية"},
    {"alpha3Code":"ATF","alpha2Code":"TF","phone":262,"name":"French Southern Territories","nameAr":"المناطق الجنوبية لفرنسا"},
    {"alpha3Code":"GAB","alpha2Code":"GA","phone":241,"name":"Gabon","nameAr":"الجابون"},
    {"alpha3Code":"GMB","alpha2Code":"GM","phone":220,"name":"Gambia","nameAr":"غامبيا"},
    {"alpha3Code":"GEO","alpha2Code":"GE","phone":995,"name":"Georgia","nameAr":"جورجيا"},
    {"alpha3Code":"DEU","alpha2Code":"DE","phone":49,"name":"Germany","nameAr":"ألمانيا"},
    {"alpha3Code":"GHA","alpha2Code":"GH","phone":233,"name":"Ghana","nameAr":"غانا"},
    {"alpha3Code":"GIB","alpha2Code":"GI","phone":350,"name":"Gibraltar","nameAr":"جبل طارق"},
    {"alpha3Code":"GRC","alpha2Code":"GR","phone":30,"name":"Greece","nameAr":"اليونان"},
    {"alpha3Code":"GRL","alpha2Code":"GL","phone":299,"name":"Greenland","nameAr":"الأرض الخضراء"},
    {"alpha3Code":"GRD","alpha2Code":"GD","phone":1473,"name":"Grenada","nameAr":"غرينادا"},
    {"alpha3Code":"GLP","alpha2Code":"GP","phone":590,"name":"Guadeloupe","nameAr":"جوادلوب"},
    {"alpha3Code":"GUM","alpha2Code":"GU","phone":1671,"name":"Guam","nameAr":"غوام"},
    {"alpha3Code":"GTM","alpha2Code":"GT","phone":502,"name":"Guatemala","nameAr":"غواتيمالا"},
    {"alpha3Code":"GGY","alpha2Code":"GG","phone":44,"name":"Guernsey","nameAr":"غيرنسي"},
    {"alpha3Code":"GIN","alpha2Code":"GN","phone":224,"name":"Guinea","nameAr":"غينيا"},
    {"alpha3Code":"GNB","alpha2Code":"GW","phone":245,"name":"Guinea-Bissau","nameAr":"غينيا بيساو"},
    {"alpha3Code":"GUY","alpha2Code":"GY","phone":592,"name":"Guyana","nameAr":"غيانا"},
    {"alpha3Code":"HTI","alpha2Code":"HT","phone":509,"name":"Haiti","nameAr":"هايتي"},
    {"alpha3Code":"HMD","alpha2Code":"HM","phone":0,"name":"Heard Island and McDonald Islands","nameAr":"قلب الجزيرة وجزر ماكدونالز"},
    {"alpha3Code":"VAT","alpha2Code":"VA","phone":39,"name":"Holy See (Vatican City State)","nameAr":"الكرسي الرسولي (دولة الفاتيكان)"},
    {"alpha3Code":"HND","alpha2Code":"HN","phone":504,"name":"Honduras","nameAr":"هندوراس"},
    {"alpha3Code":"HKG","alpha2Code":"HK","phone":852,"name":"Hong Kong","nameAr":"هونج كونج"},
    {"alpha3Code":"HUN","alpha2Code":"HU","phone":36,"name":"Hungary","nameAr":"هنغاريا"},
    {"alpha3Code":"ISL","alpha2Code":"IS","phone":354,"name":"Iceland","nameAr":"أيسلندا"},
    {"alpha3Code":"IND","alpha2Code":"IN","phone":91,"name":"India","nameAr":"الهند"},
    {"alpha3Code":"IDN","alpha2Code":"ID","phone":62,"name":"Indonesia","nameAr":"إندونيسيا"},
    {"alpha3Code":"IRN","alpha2Code":"IR","phone":98,"name":"Iran, Islamic Republic of","nameAr":"جمهورية إيران الإسلامية"},
    {"alpha3Code":"IRQ","alpha2Code":"IQ","phone":964,"name":"Iraq","nameAr":"العراق"},
    {"alpha3Code":"IRL","alpha2Code":"IE","phone":353,"name":"Ireland","nameAr":"أيرلندا"},
    {"alpha3Code":"IMN","alpha2Code":"IM","phone":44,"name":"Isle of Man","nameAr":"جزيرة آيل أوف مان"},
    {"alpha3Code":"ISR","alpha2Code":"IL","phone":972,"name":"Israel","nameAr":"إسرائيل"},
    {"alpha3Code":"ITA","alpha2Code":"IT","phone":39,"name":"Italy","nameAr":"إيطاليا"},
    {"alpha3Code":"JAM","alpha2Code":"JM","phone":1876,"name":"Jamaica","nameAr":"جامايكا"},
    {"alpha3Code":"JPN","alpha2Code":"JP","phone":81,"name":"Japan","nameAr":"اليابان"},
    {"alpha3Code":"JEY","alpha2Code":"JE","phone":44,"name":"Jersey","nameAr":"جيرسي"},
    {"alpha3Code":"JOR","alpha2Code":"JO","phone":962,"name":"Jordan","nameAr":"الأردن"},
    {"alpha3Code":"KAZ","alpha2Code":"KZ","phone":7,"name":"Kazakhstan","nameAr":"كازاخستان"},
    {"alpha3Code":"KEN","alpha2Code":"KE","phone":254,"name":"Kenya","nameAr":"كينيا"},
    {"alpha3Code":"KIR","alpha2Code":"KI","phone":686,"name":"Kiribati","nameAr":"كيريباتي"},
    {"alpha3Code":"PRK","alpha2Code":"KP","phone":850,"name":"Korea, Democratic People's Republic of","nameAr":"كوريا، الجمهورية الشعبية الديمقراطية"},
    {"alpha3Code":"KOR","alpha2Code":"KR","phone":82,"name":"Korea, Republic of","nameAr":"جمهورية كوريا"},
    {"alpha3Code":"XKX","alpha2Code":"XK","phone":381,"name":"Kosovo","nameAr":"كوسوفو"},
    {"alpha3Code":"KWT","alpha2Code":"KW","phone":965,"name":"Kuwait","nameAr":"الكويت"},
    {"alpha3Code":"KGZ","alpha2Code":"KG","phone":996,"name":"Kyrgyzstan","nameAr":"قيرغيزستان"},
    {"alpha3Code":"LAO","alpha2Code":"LA","phone":856,"name":"Lao People's Democratic Republic","nameAr":"جمهورية لاو الديمقراطية الشعبية"},
    {"alpha3Code":"LVA","alpha2Code":"LV","phone":371,"name":"Latvia","nameAr":"لاتفيا"},
    {"alpha3Code":"LBN","alpha2Code":"LB","phone":961,"name":"Lebanon","nameAr":"لبنان"},
    {"alpha3Code":"LSO","alpha2Code":"LS","phone":266,"name":"Lesotho","nameAr":"ليسوتو"},
    {"alpha3Code":"LBR","alpha2Code":"LR","phone":231,"name":"Liberia","nameAr":"ليبيريا"},
    {"alpha3Code":"LBY","alpha2Code":"LY","phone":218,"name":"Libyan Arab Jamahiriya","nameAr":"الجماهيرية العربية الليبية"},
    {"alpha3Code":"LIE","alpha2Code":"LI","phone":423,"name":"Liechtenstein","nameAr":"ليختنشتاين"},
    {"alpha3Code":"LTU","alpha2Code":"LT","phone":370,"name":"Lithuania","nameAr":"ليتوانيا"},
    {"alpha3Code":"LUX","alpha2Code":"LU","phone":352,"name":"Luxembourg","nameAr":"لوكسمبورغ"},
    {"alpha3Code":"MAC","alpha2Code":"MO","phone":853,"name":"Macao","nameAr":"ماكاو"},
    {"alpha3Code":"MKD","alpha2Code":"MK","phone":389,"name":"Macedonia, the Former Yugoslav Republic of","nameAr":"مقدونيا ، جمهورية يوغوسلافيا السابقة"},
    {"alpha3Code":"MDG","alpha2Code":"MG","phone":261,"name":"Madagascar","nameAr":"مدغشقر"},
    {"alpha3Code":"MWI","alpha2Code":"MW","phone":265,"name":"Malawi","nameAr":"ملاوي"},
    {"alpha3Code":"MYS","alpha2Code":"MY","phone":60,"name":"Malaysia","nameAr":"ماليزيا"},
    {"alpha3Code":"MDV","alpha2Code":"MV","phone":960,"name":"Maldives","nameAr":"جزر المالديف"},
    {"alpha3Code":"MLI","alpha2Code":"ML","phone":223,"name":"Mali","nameAr":"مالي"},
    {"alpha3Code":"MLT","alpha2Code":"MT","phone":356,"name":"Malta","nameAr":"مالطا"},
    {"alpha3Code":"MHL","alpha2Code":"MH","phone":692,"name":"Marshall Islands","nameAr":"جزر مارشال"},
    {"alpha3Code":"MTQ","alpha2Code":"MQ","phone":596,"name":"Martinique","nameAr":"مارتينيك"},
    {"alpha3Code":"MRT","alpha2Code":"MR","phone":222,"name":"Mauritania","nameAr":"موريتانيا"},
    {"alpha3Code":"MUS","alpha2Code":"MU","phone":230,"name":"Mauritius","nameAr":"موريشيوس"},
    {"alpha3Code":"MYT","alpha2Code":"YT","phone":269,"name":"Mayotte","nameAr":"مايوت"},
    {"alpha3Code":"MEX","alpha2Code":"MX","phone":52,"name":"Mexico","nameAr":"المكسيك"},
    {"alpha3Code":"FSM","alpha2Code":"FM","phone":691,"name":"Micronesia, Federated States of","nameAr":"ولايات ميكرونيزيا الموحدة"},
    {"alpha3Code":"MDA","alpha2Code":"MD","phone":373,"name":"Moldova, Republic of","nameAr":"جمهورية مولدوفا"},
    {"alpha3Code":"MCO","alpha2Code":"MC","phone":377,"name":"Monaco","nameAr":"موناكو"},
    {"alpha3Code":"MNG","alpha2Code":"MN","phone":976,"name":"Mongolia","nameAr":"منغوليا"},
    {"alpha3Code":"MNE","alpha2Code":"ME","phone":382,"name":"Montenegro","nameAr":"الجبل الأسود"},
    {"alpha3Code":"MSR","alpha2Code":"MS","phone":1664,"name":"Montserrat","nameAr":"مونتسيرات"},
    {"alpha3Code":"MAR","alpha2Code":"MA","phone":212,"name":"Morocco","nameAr":"المغرب"},
    {"alpha3Code":"MOZ","alpha2Code":"MZ","phone":258,"name":"Mozambique","nameAr":"موزمبيق"},
    {"alpha3Code":"MMR","alpha2Code":"MM","phone":95,"name":"Myanmar","nameAr":"ميانمار"},
    {"alpha3Code":"NAM","alpha2Code":"NA","phone":264,"name":"Namibia","nameAr":"ناميبيا"},
    {"alpha3Code":"NRU","alpha2Code":"NR","phone":674,"name":"Nauru","nameAr":"ناورو"},
    {"alpha3Code":"NPL","alpha2Code":"NP","phone":977,"name":"Nepal","nameAr":"نيبال"},
    {"alpha3Code":"NLD","alpha2Code":"NL","phone":31,"name":"Netherlands","nameAr":"هولندا"},
    {"alpha3Code":"ANT","alpha2Code":"AN","phone":599,"name":"Netherlands Antilles","nameAr":"جزر الأنتيل الهولندية"},
    {"alpha3Code":"NCL","alpha2Code":"NC","phone":687,"name":"New Caledonia","nameAr":"كاليدونيا الجديدة"},
    {"alpha3Code":"NZL","alpha2Code":"NZ","phone":64,"name":"New Zealand","nameAr":"نيوزيلاندا"},
    {"alpha3Code":"NIC","alpha2Code":"NI","phone":505,"name":"Nicaragua","nameAr":"نيكاراغوا"},
    {"alpha3Code":"NER","alpha2Code":"NE","phone":227,"name":"Niger","nameAr":"النيجر"},
    {"alpha3Code":"NGA","alpha2Code":"NG","phone":234,"name":"Nigeria","nameAr":"نيجيريا"},
    {"alpha3Code":"NIU","alpha2Code":"NU","phone":683,"name":"Niue","nameAr":"نيوي"},
    {"alpha3Code":"NFK","alpha2Code":"NF","phone":672,"name":"Norfolk Island","nameAr":"جزيرة نورفولك"},
    {"alpha3Code":"MNP","alpha2Code":"MP","phone":1670,"name":"Northern Mariana Islands","nameAr":"جزر مريانا الشمالية"},
    {"alpha3Code":"NOR","alpha2Code":"NO","phone":47,"name":"Norway","nameAr":"النرويج"},
    {"alpha3Code":"OMN","alpha2Code":"OM","phone":968,"name":"Oman","nameAr":"سلطنة عمان"},
    {"alpha3Code":"PAK","alpha2Code":"PK","phone":92,"name":"Pakistan","nameAr":"باكستان"},
    {"alpha3Code":"PLW","alpha2Code":"PW","phone":680,"name":"Palau","nameAr":"بالاو"},
    {"alpha3Code":"PSE","alpha2Code":"PS","phone":970,"name":"Palestinian Territory, Occupied","nameAr":"الأراضي الفلسطينية المحتلة"},
    {"alpha3Code":"PAN","alpha2Code":"PA","phone":507,"name":"Panama","nameAr":"بنما"},
    {"alpha3Code":"PNG","alpha2Code":"PG","phone":675,"name":"Papua New Guinea","nameAr":"بابوا غينيا الجديدة"},
    {"alpha3Code":"PRY","alpha2Code":"PY","phone":595,"name":"Paraguay","nameAr":"باراغواي"},
    {"alpha3Code":"PER","alpha2Code":"PE","phone":51,"name":"Peru","nameAr":"بيرو"},
    {"alpha3Code":"PHL","alpha2Code":"PH","phone":63,"name":"Philippines","nameAr":"فيلبيني"},
    {"alpha3Code":"PCN","alpha2Code":"PN","phone":64,"name":"Pitcairn","nameAr":"بيتكيرن"},
    {"alpha3Code":"POL","alpha2Code":"PL","phone":48,"name":"Poland","nameAr":"بولندا"},
    {"alpha3Code":"PRT","alpha2Code":"PT","phone":351,"name":"Portugal","nameAr":"البرتغال"},
    {"alpha3Code":"PRI","alpha2Code":"PR","phone":1787,"name":"Puerto Rico","nameAr":"بورتوريكو"},
    {"alpha3Code":"QAT","alpha2Code":"QA","phone":974,"name":"Qatar","nameAr":"دولة قطر"},
    {"alpha3Code":"REU","alpha2Code":"RE","phone":262,"name":"Reunion","nameAr":"جمع شمل"},
    {"alpha3Code":"ROM","alpha2Code":"RO","phone":40,"name":"Romania","nameAr":"رومانيا"},
    {"alpha3Code":"RUS","alpha2Code":"RU","phone":70,"name":"Russian Federation","nameAr":"الاتحاد الروسي"},
    {"alpha3Code":"RWA","alpha2Code":"RW","phone":250,"name":"Rwanda","nameAr":"رواندا"},
    {"alpha3Code":"BLM","alpha2Code":"BL","phone":590,"name":"Saint Barthelemy","nameAr":"سانت بارتيليمي"},
    {"alpha3Code":"SHN","alpha2Code":"SH","phone":290,"name":"Saint Helena","nameAr":"سانت هيلانة"},
    {"alpha3Code":"KNA","alpha2Code":"KN","phone":1869,"name":"Saint Kitts and Nevis","nameAr":"سانت كيتس ونيفيس"},
    {"alpha3Code":"LCA","alpha2Code":"LC","phone":1758,"name":"Saint Lucia","nameAr":"القديسة لوسيا"},
    {"alpha3Code":"MAF","alpha2Code":"MF","phone":590,"name":"Saint Martin","nameAr":"القديس مارتن"},
    {"alpha3Code":"SPM","alpha2Code":"PM","phone":508,"name":"Saint Pierre and Miquelon","nameAr":"سانت بيير وميكلون"},
    {"alpha3Code":"VCT","alpha2Code":"VC","phone":1784,"name":"Saint Vincent and the Grenadines","nameAr":"سانت فنسنت وجزر غرينادين"},
    {"alpha3Code":"WSM","alpha2Code":"WS","phone":684,"name":"Samoa","nameAr":"ساموا"},
    {"alpha3Code":"SMR","alpha2Code":"SM","phone":378,"name":"San Marino","nameAr":"سان مارينو"},
    {"alpha3Code":"STP","alpha2Code":"ST","phone":239,"name":"Sao Tome and Principe","nameAr":"ساو تومي وبرينسيبي"},
    {"alpha3Code":"SAU","alpha2Code":"SA","phone":966,"name":"Saudi Arabia","nameAr":"المملكة العربية السعودية"},
    {"alpha3Code":"SEN","alpha2Code":"SN","phone":221,"name":"Senegal","nameAr":"السنغال"},
    {"alpha3Code":"SRB","alpha2Code":"RS","phone":381,"name":"Serbia","nameAr":"صربيا"},
    {"alpha3Code":"SCG","alpha2Code":"CS","phone":381,"name":"Serbia and Montenegro","nameAr":"صربيا والجبل الأسود"},
    {"alpha3Code":"SYC","alpha2Code":"SC","phone":248,"name":"Seychelles","nameAr":"سيشيل"},
    {"alpha3Code":"SLE","alpha2Code":"SL","phone":232,"name":"Sierra Leone","nameAr":"سيرا ليون"},
    {"alpha3Code":"SGP","alpha2Code":"SG","phone":65,"name":"Singapore","nameAr":"سنغافورة"},
    {"alpha3Code":"SXM","alpha2Code":"SX","phone":1,"name":"St Martin","nameAr":"سينت مارتن"},
    {"alpha3Code":"SVK","alpha2Code":"SK","phone":421,"name":"Slovakia","nameAr":"سلوفاكيا"},
    {"alpha3Code":"SVN","alpha2Code":"SI","phone":386,"name":"Slovenia","nameAr":"سلوفينيا"},
    {"alpha3Code":"SLB","alpha2Code":"SB","phone":677,"name":"Solomon Islands","nameAr":"جزر سليمان"},
    {"alpha3Code":"SOM","alpha2Code":"SO","phone":252,"name":"Somalia","nameAr":"الصومال"},
    {"alpha3Code":"ZAF","alpha2Code":"ZA","phone":27,"name":"South Africa","nameAr":"جنوب أفريقيا"},
    {"alpha3Code":"SGS","alpha2Code":"GS","phone":500,"name":"South Georgia and the South Sandwich Islands","nameAr":"جورجيا الجنوبية وجزر ساندويتش الجنوبية"},
    {"alpha3Code":"SSD","alpha2Code":"SS","phone":211,"name":"South Sudan","nameAr":"جنوب السودان"},
    {"alpha3Code":"ESP","alpha2Code":"ES","phone":34,"name":"Spain","nameAr":"إسبانيا"},
    {"alpha3Code":"LKA","alpha2Code":"LK","phone":94,"name":"Sri Lanka","nameAr":"سيريلانكا"},
    {"alpha3Code":"SDN","alpha2Code":"SD","phone":249,"name":"Sudan","nameAr":"السودان"},
    {"alpha3Code":"SUR","alpha2Code":"SR","phone":597,"name":"Suriname","nameAr":"سورينام"},
    {"alpha3Code":"SJM","alpha2Code":"SJ","phone":47,"name":"Svalbard and Jan Mayen","nameAr":"سفالبارد وجان ماين"},
    {"alpha3Code":"SWZ","alpha2Code":"SZ","phone":268,"name":"Swaziland","nameAr":"سوازيلاند"},
    {"alpha3Code":"SWE","alpha2Code":"SE","phone":46,"name":"Sweden","nameAr":"السويد"},
    {"alpha3Code":"CHE","alpha2Code":"CH","phone":41,"name":"Switzerland","nameAr":"سويسرا"},
    {"alpha3Code":"SYR","alpha2Code":"SY","phone":963,"name":"Syrian Arab Republic","nameAr":"الجمهورية العربية السورية"},
    {"alpha3Code":"TWN","alpha2Code":"TW","phone":886,"name":"Taiwan, Province of China","nameAr":"مقاطعة تايوان الصينية"},
    {"alpha3Code":"TJK","alpha2Code":"TJ","phone":992,"name":"Tajikistan","nameAr":"طاجيكستان"},
    {"alpha3Code":"TZA","alpha2Code":"TZ","phone":255,"name":"Tanzania, United Republic of","nameAr":"جمهورية تنزانيا المتحدة"},
    {"alpha3Code":"THA","alpha2Code":"TH","phone":66,"name":"Thailand","nameAr":"تايلاند"},
    {"alpha3Code":"TLS","alpha2Code":"TL","phone":670,"name":"Timor-Leste","nameAr":"تيمور ليشتي"},
    {"alpha3Code":"TGO","alpha2Code":"TG","phone":228,"name":"Togo","nameAr":"توجو"},
    {"alpha3Code":"TKL","alpha2Code":"TK","phone":690,"name":"Tokelau","nameAr":"توكيلاو"},
    {"alpha3Code":"TON","alpha2Code":"TO","phone":676,"name":"Tonga","nameAr":"تونغا"},
    {"alpha3Code":"TTO","alpha2Code":"TT","phone":1868,"name":"Trinidad and Tobago","nameAr":"ترينداد وتوباغو"},
    {"alpha3Code":"TUN","alpha2Code":"TN","phone":216,"name":"Tunisia","nameAr":"تونس"},
    {"alpha3Code":"TUR","alpha2Code":"TR","phone":90,"name":"Turkey","nameAr":"ديك رومى"},
    {"alpha3Code":"TKM","alpha2Code":"TM","phone":7370,"name":"Turkmenistan","nameAr":"تركمانستان"},
    {"alpha3Code":"TCA","alpha2Code":"TC","phone":1649,"name":"Turks and Caicos Islands","nameAr":"جزر تركس وكايكوس"},
    {"alpha3Code":"TUV","alpha2Code":"TV","phone":688,"name":"Tuvalu","nameAr":"توفالو"},
    {"alpha3Code":"UGA","alpha2Code":"UG","phone":256,"name":"Uganda","nameAr":"أوغندا"},
    {"alpha3Code":"UKR","alpha2Code":"UA","phone":380,"name":"Ukraine","nameAr":"أوكرانيا"},
    {"alpha3Code":"ARE","alpha2Code":"AE","phone":971,"name":"United Arab Emirates","nameAr":"الإمارات العربية المتحدة"},
    {"alpha3Code":"GBR","alpha2Code":"GB","phone":44,"name":"United Kingdom","nameAr":"المملكة المتحدة"},
    {"alpha3Code":"USA","alpha2Code":"US","phone":1,"name":"United States","nameAr":"الولايات المتحدة"},
    {"alpha3Code":"UMI","alpha2Code":"UM","phone":1,"name":"United States Minor Outlying Islands","nameAr":"جزر الولايات المتحدة البعيدة الصغرى"},
    {"alpha3Code":"URY","alpha2Code":"UY","phone":598,"name":"Uruguay","nameAr":"أوروغواي"},
    {"alpha3Code":"UZB","alpha2Code":"UZ","phone":998,"name":"Uzbekistan","nameAr":"أوزبكستان"},
    {"alpha3Code":"VUT","alpha2Code":"VU","phone":678,"name":"Vanuatu","nameAr":"فانواتو"},
    {"alpha3Code":"VEN","alpha2Code":"VE","phone":58,"name":"Venezuela","nameAr":"فنزويلا"},
    {"alpha3Code":"VNM","alpha2Code":"VN","phone":84,"name":"Viet Nam","nameAr":"فييت نام"},
    {"alpha3Code":"VGB","alpha2Code":"VG","phone":1284,"name":"Virgin Islands, British","nameAr":"جزر العذراء البريطانية"},
    {"alpha3Code":"VIR","alpha2Code":"VI","phone":1340,"name":"Virgin Islands, U.s.","nameAr":"جزر فيرجن ، الولايات المتحدة"},
    {"alpha3Code":"WLF","alpha2Code":"WF","phone":681,"name":"Wallis and Futuna","nameAr":"واليس وفوتونا"},
    {"alpha3Code":"ESH","alpha2Code":"EH","phone":212,"name":"Western Sahara","nameAr":"الصحراء الغربية"},
    {"alpha3Code":"YEM","alpha2Code":"YE","phone":967,"name":"Yemen","nameAr":"اليمن"},
    {"alpha3Code":"ZMB","alpha2Code":"ZM","phone":260,"name":"Zambia","nameAr":"زامبيا"},
    {"alpha3Code":"ZWE","alpha2Code":"ZW","phone":263,"name":"Zimbabwe","nameAr":"زيمبابوي"}
]
