name: docker-1
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: .
          file_name: .env
          fail_on_empty: false
          envkey_PUBLIC_AQARATECH_ENV: development
          envkey_PUBLIC_SITE_URL: http://site:3000
          envkey_PUBLIC_API_URL: http://backend:3002
          envkey_PUBLIC_API_URL_LOCAL: http://backend:3002
          envkey_AUTH0_CLIENT_SECRET: uSR4Gjf3XNN-1kfZGuppDqRdbz7XD6A4o2g8yY1GdZgqCXeYhWhdqfPUoIIJLBRf
          envkey_PUBLIC_TRACE_RATE: 0
          envkey_PUBLIC_AQ_DEBUG_SITE: 0
          envkey_PUBLIC_AQ_DEBUG_SENTRY: 0
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network aq-network appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/
      - name: Test2
        run: docker run --network aq-network appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3002/
