name: docker-build-test
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: environment-1
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: .
          file_name: .env
          fail_on_empty: false
          envkey_PUBLIC_AQARATECH_ENV: development
          envkey_PUBLIC_SITE_URL: http://site:3000
          envkey_PUBLIC_API_URL: http://backend:3002
          envkey_PUBLIC_API_URL_LOCAL: http://backend:3002
          envkey_AUTH0_CLIENT_SECRET: uSR4Gjf3XNN-1kfZGuppDqRdbz7XD6A4o2g8yY1GdZgqCXeYhWhdqfPUoIIJLBRf
          envkey_PUBLIC_TRACE_RATE: 0
          envkey_PUBLIC_AQ_DEBUG_SITE: 0
          envkey_PUBLIC_AQ_DEBUG_SENTRY: 0

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Bake stack
        uses: docker/bake-action@v2.2.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          push: false
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
        continue-on-error: true

      - name: Run the stack
        run: docker-compose up -d --no-build
        continue-on-error: true

      - name: Build tester
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./packages/test/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          load: true
          tags: tester
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: docker run --rm --network host tester
        continue-on-error: true
