# this should call ci with the dev environment inputs
name: CI - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      environment: dev
      appName: ${{ github.ref_name }}
      # TODO: It'd be nice to skip building unchanged images
      siteTag: ${{  github.ref_name  }}
      backendTag: ${{  github.ref_name  }}
