# this should call ci with the dev environment inputs
name: CI - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  run-ci:
    # if triggered by pull_request event, only run if PR has label "preview"
    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'preview') }}

    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      environment: dev
      # Use PR head branch name if PR, otherwise use branch name
      appName: ${{  github.head_ref || github.ref_name }}
      # change to github.sha when we add the sha to Sentry.init
      siteSentryRelease: ${{ github.sha }}
      backendSentryRelease: ${{ github.sha }}
      # TODO: It'd be nice to skip building unchanged images
      # if branch is master, set siteTag to latest, otherwise use branch name
      siteTag: ${{ github.sha }}
      backendTag: ${{  github.sha }}
