name: Playwright Tests

on:
  push:
    branches: [stage, prod]
  pull_request:
    branches: [stage, prod]

env:
  REUSE_PRISMA: 1
  DATABASE_URL: "mysql://862k5346c5q6:pscale_pw_aETUs5s9KQhjsjkoxuamsqyn-c2VmpqVGPSBvVJxTS0@kz17sp33s8ut.ap-south-2.psdb.cloud/aqaratechdb?sslaccept=strict&pool_timeout=0"

jobs:
  test:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          # cache: "pnpm"
      - name: Install & build dependencies
        run: pnpm --filter "@self/site-test^..." install && pnpm --filter "@self/site-test^..." run package
      - name: Install @self/test dependencies
        run: pnpm --filter "@self/site-test" install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm --filter "@self/site-test" test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
