name: Playwright Tests

on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

env:
  REUSE_PRISMA: 1
  DATABASE_URL: "mysql://lp5w7h865rnm:pscale_pw_HuGMgxfTQ4X1-bW1BXm0xkYNnIBhjX5o4BjPP8G8cqE@kz17sp33s8ut.ap-south-2.psdb.cloud/aqaratechdb?sslaccept=strict"

jobs:
  test:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          # cache: "pnpm" // TODO: add back
      - name: Install all
        run: pnpm install -r --no-frozen-lockfile
      - name: Install & build dependencies
        run: pnpm --filter "@self/site" run package && pnpm --filter "@self/seed" run package
      - name: Install @self/test dependencies
        run: pnpm --filter "@self/site-test" install --no-frozen-lockfile
      - name: Install Playwright
        run: npx playwright@1.21.1 install --with-deps
      - name: Run Playwright tests
        run: pnpm --filter "@self/site-test" test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
