name: Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - prod

jobs:
  prepare-prod:
    runs-on: ubuntu-latest
    # Use dev environment to allow master branch to run this workflow
    environment: dev
    env:
      NEW_SITE_TAG: v1.0.0-sample
      NEW_BACKEND_TAG: v1.0.0-sample
      DOCKER_PREFIX: registry.digitalocean.com/aqtech/aqaratech

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        shell: bash
        run: doctl registry login --expiry-seconds 600

      - name: Retag site
        shell: bash
        run: |
          docker pull ${{ env.DOCKER_PREFIX }}-site:master
          docker tag ${{ env.DOCKER_PREFIX }}-site:master ${{ env.DOCKER_PREFIX }}-site:${{ env.NEW_SITE_TAG }}
          docker push ${{ env.DOCKER_PREFIX }}-site:${{ env.NEW_SITE_TAG }}

      - name: Retag backend
        shell: bash
        run: |
          docker pull ${{ env.DOCKER_PREFIX }}-backend:master
          docker tag ${{ env.DOCKER_PREFIX }}-backend:master ${{ env.DOCKER_PREFIX }}-backend:${{ env.NEW_BACKEND_TAG }}
          docker push ${{ env.DOCKER_PREFIX }}-backend:${{ env.NEW_BACKEND_TAG }}
