name: Release

on:
  workflow_call:

jobs:
  release:
    name: Release
    id: release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.27.5

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create deployment on DigitalOcean
        shell: bash
        run: |
          ./.do/deploy.sh
        env:
          DO_PROJECT_ID: ${{ secrets.DO_PROJECT_ID }}
          DO_APP_NAME: ${{ github.ref }}
