name: Release

on:
  push:
    branches:
      - master
env:
  CI: true
  # https://pnpm.io/using-changesets
  # PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  create-release-PR:
    runs-on: ubuntu-latest
    environment: prod

    outputs:
      siteTag: ${{ steps.changesets.outputs.siteTag }}
      backendTag: ${{ steps.pkgversions.outputs.backendTag }}
      published: ${{ steps.pkgversions.outputs.published }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # https://github.com/changesets/action/issues/200#issuecomment-1225472569
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      # If there are changesets, open a PR with the new versions
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          # `version` consumes changesets + creates/updates PR. Run when there are changesets.
          version: pnpm ci:version
          # `publish` creates tags + releases on github. Runs when no changesets are present (or have been just consumed by `version`).
          publish: pnpm ci:publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug changesets output
        shell: bash
        run: |
          echo ${{ steps.changesets.outputs.publishedPackages }}
          echo ${{ steps.changesets.outputs.published }}
          echo ${{ steps.changesets.outputs.hasChangesets }}

      # Sample publishedPackages: [{"name":"@self/backend","version":"0.3.4"},{"name":"@self/docs","version":"0.3.4"},{"name":"@self/seed","version":"0.3.4"},{"name":"@self/site","version":"0.4.6"},{"name":"@self/test","version":"1.3.4"},{"name":"@self/utils","version":"1.3.4"}]
      - id: pkgversions
        run: |
          echo ${{ steps.changesets.outputs.publishedPackages }} > publishedPackages.json
          SITE_TAG=$(jq -r '.[] | select(.name == "@self/site") | .version' publishedPackages.json)
          BACKEND_TAG=$(jq -r '.[] | select(.name == "@self/backend") | .version' publishedPackages.json)
          echo "::set-output name=siteTag::${SITE_TAG}"
          echo "::set-output name=backendTag::${BACKEND_TAG}"

  publish:
    needs: [create-release-PR]
    # Run this job when changesets publishes a new version
    if: ${{ needs.create-release-PR.outputs.published == 'true' }}
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      environment: prod
      appName: aqaratech-app-prod
      siteTag: ${{ needs.create-release-PR.outputs.siteTag }}
      backendTag: ${{ needs.create-release-PR.outputs.backendTag }}
