name: Release

on:
  push:
    branches:
      - master
env:
  CI: true
  # https://pnpm.io/using-changesets
  # PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  create-release-PR:
    runs-on: ubuntu-latest
    environment: prod

    outputs:
      siteTag: ${{ steps.changesets.outputs.siteTag }}
      backendTag: ${{ steps.step1.outputs.backendTag }}
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      # If there are changesets, open a PR with the new versions
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug changesets output
        shell: bash
        run: |
          echo ${{ steps.changesets.outputs.publishedPackages }}
          echo ${{ steps.changesets.outputs.published }}
          echo ${{ steps.changesets.outputs.hasChangesets }}

  release:
    needs: [create-release-PR]
    # Once the PR is merged, this job will build the docker images and trigger a new deployment on DigitalOcean
    # TODO: handle cases where there are no changesets, but it doesn't make sense to deploy
    if: ${{ needs.create-release-PR.outputs.hasChangesets == 'falseDELETEME' }}
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      environment: prod
      appName: aqaratech-app-prod
      siteTag: ${{ needs.create-release-PR.outputs.siteTag }}
      backendTag: ${{ needs.create-release-PR.outputs.backendTag }}
