name: Seed stage db

on:
  workflow_dispatch:
    inputs:
      db_url:
        description: 'URL of database to seed'
        required: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  seed:
    name: Seed
    timeout-minutes: 5
    # TODO, find way to restrict access to DigitalOcean prod projects entirely from github's dev environment
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main

      - name: Install deps (seed & backend)
        run: nix develop --command pnpm -F . -F @self/seed... -F @self/backend... install --frozen-lockfile

      - name: Build deps (seed & backend)
        run: nix develop --command pnpm turbo run build --filter=@self/backend --filter=@self/seed

      - name: Seed db
        run: nix develop --command pnpm -F @self/backend exec prisma migrate reset --force
        env:
          DATABASE_URL: ${{ github.event.inputs.db_url }}
          PUBLIC_AQARATECH_ENV: 'staging'
          R2_ENDPOINT: 'https://8aa55983de332834393a9f4c4fbf1e35.r2.cloudflarestorage.com'
          R2_ACCESS_KEY_ID: '19c40a5035eeb256b8e2fd59811c7203'
          R2_SECRET_ACCESS_KEY: '2493bd85d0e72adb6979a06c6385468653693f99dc8b108a655de336e3a04bb1'
