name: Teardown DigitalOcean Resources

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  destroy:
    environment: dev
    runs-on: ubuntu-latest
    # don't run for changeset-release branches
    if: ${{ github.event.ref != 'changeset-release/master' }}
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - uses: actions/checkout@v3

      - name: destroy app
        shell: bash
        run: |
          echo "DELETED_BRANCH_REF is $DELETED_BRANCH_REF"
          DELETED_BRANCH_NAME=$(echo $DELETED_BRANCH_REF | sed -e "s#refs/heads/##g")
          echo "DELETED_BRANCH_NAME is $DELETED_BRANCH_NAME"
          ./.do/teardown.sh $DELETED_BRANCH_NAME ${{ secrets.DO_PROJECT_ID }}
        env:
          DELETED_BRANCH_REF: ${{ github.head_ref || github.event.ref }}
