name: Delete App on DigitalOcean

# Deleting a branch should cancel any ongoing tests/deployments for that branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  delete:

jobs:
  destroy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ inputs.token }}

      - uses: actions/checkout@v3

      - shell: bash
        run: ./.do/teardown ${{ github.ref_name }} ${{ secrets.DO_PROJECT_ID }}
