name: Teardown DigitalOcean Resources

on:
  workflow_dispatch:
  pull_request:
    types: [closed, unlabeled]

jobs:
  destroy:
    # Prevent the job from running when *any* of the following conditions are met:
    # 1. The github.event.ref is not 'changeset-release/master'
    # 2. A pr was unlabeled and the removed label does not contain "preview"
    if: ${{ github.event.ref != 'refs/heads/changeset-release/master' && !(github.event.pull_request.labels.contains('preview') && github.event.action == 'unlabeled') }}

    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - uses: actions/checkout@v3

      - name: destroy app
        shell: bash
        run: |
          echo "DELETED_BRANCH_REF is $DELETED_BRANCH_REF"
          DELETED_BRANCH_NAME=$(echo $DELETED_BRANCH_REF | sed -e "s#refs/heads/##g")
          echo "DELETED_BRANCH_NAME is $DELETED_BRANCH_NAME"
          ./.do/teardown.sh $DELETED_BRANCH_NAME ${{ secrets.DO_PROJECT_ID }}
        env:
          DELETED_BRANCH_REF: ${{ github.head_ref || github.event.ref }}
