name: Teardown DigitalOcean Resources

# Deleting a branch should cancel any ongoing tests/deployments for that branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  delete:
  workflow_dispatch:

jobs:
  destroy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - uses: actions/checkout@v3

      - name: destroy app
        shell: bash
        run: |
          echo "::set-env name=DELETED_BRANCH_REF::${{ github.event.ref }}"
          echo "DELETED_BRANCH_REF is $DELETED_BRANCH_REF"
          DELETED_BRANCH_NAME=$(echo $DELETED_BRANCH_REF | sed -e "s#refs/heads/##g")
          echo "DELETED_BRANCH_NAME is $DELETED_BRANCH_NAME"
          ./.do/teardown.sh $DELETED_BRANCH_NAME ${{ secrets.DO_PROJECT_ID }}
