name: CI-test-native
on: workflow_dispatch

jobs:
  test:
    name: Build and Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: Set .env file
        run: cp ./.env.ci ./.env

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: cd packages/test && npx playwright install --with-deps

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: |
            packages/test/playwright-report/
            packages/test/test-results/

  push:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set .env file
        run: cp ./.env.ci ./.env

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.site
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          load: false
          tags: registry.digitalocean.com/aqtech/aqaratech-site:$(grep '"version":' ./packages/site/package.json | awk '{print $2}' | tr -d '",')-$(echo $GITHUB_SHA | head -c7)

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.backend
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          load: false
          tags: registry.digitalocean.com/aqtech/aqaratech-backend:$(grep '"version":' ./packages/backend/package.json | awk '{print $2}' | tr -d '",')-$(echo $GITHUB_SHA | head -c7)
